export const adsLiveCopy: Record<string, string> = {
  'Several active subscriptions need review.': 'تحتاج الاشتراكات النشطة المتعددة إلى مراجعة.',
  'The place needs a picture or video.': 'يحتاج المكان إلى صورة أو فيديو.', 'The place is not active.': 'المكان غير نشط.',
  'The place is still a draft.': 'المكان لا يزال مسودة.', 'The subscription has expired.': 'انتهى الاشتراك.',
  'The subscription has not started.': 'لم يبدأ الاشتراك بعد.', 'The subscription is in its grace period.': 'الاشتراك في فترة السماح.',
  'Manual access does not include plan promotion.': 'الوصول اليدوي لا يتضمن ترويج الخطط.',
  'Impression': 'ظهور', 'Stopped': 'متوقف', 'Running': 'جارٍ', 'Editorial': 'تحريري', 'Editorial pin': 'تثبيت تحريري', 'Language': 'اللغة',
  'Manual promotions have no end date. Owner Plus promotions come from the plan and are read-only here.': 'الترويج اليدوي بلا موعد انتهاء. يأتي ترويج المالك بلس من الخطة ويُعرض هنا للقراءة فقط.',
  'Manual totals are lifetime accepted campaign counters; plan totals cover the report range. Do not add them as one period.': 'الإجماليات اليدوية تخص النشاط المقبول طوال عمر الحملة؛ وإجماليات الخطط تخص فترة التقرير. لا تجمعها كفترة واحدة.',
  'Current order; refresh to see the next rotation.': 'الترتيب الحالي؛ حدث المعاينة لرؤية التدوير التالي.',
  'Incomplete export': 'تصدير غير مكتمل',
  'Decisions first: expiring agreements, exposure to check and space worth selling.': 'القرارات أولًا: اتفاقات توشك على الانتهاء، وظهور يحتاج مراجعة، ومساحات تستحق البيع.',
  'Drag a section or use Move up and Move down. The whole order is saved together. Changes are live at once.': 'اسحب القسم أو استخدم التحريك لأعلى ولأسفل. يُحفظ الترتيب كاملًا معًا وتظهر التغييرات فورًا.',
  'Could not update homepage sections.': 'تعذر تحديث أقسام الصفحة الرئيسية.',
  'Manage places': 'إدارة الأماكن', 'Could not search places. Try again.': 'تعذر البحث عن الأماكن. حاول مجددًا.', 'Expiry stays unchanged': 'يبقى موعد الانتهاء دون تغيير',
  'Live is switched off; enabling it requires LIVE_STATUS_ENABLED=on and a backend restart with healthy Redis.': 'النشاط المباشر معطل؛ يتطلب تفعيله ضبط LIVE_STATUS_ENABLED=on وإعادة تشغيل الخادم مع Redis يعمل بصورة سليمة.',
  'Live activity is temporarily unavailable. No empty counts have been substituted.': 'النشاط المباشر غير متاح مؤقتًا. لم نستبدله بعدادات فارغة.',
  'Dropped or unconfirmed events on this backend instance since boot, not a window or fleet total.': 'أحداث لم تُحتسب أو لم تُؤكد على نسخة الخادم هذه منذ تشغيلها، وليست إجمالي الفترة أو كل الخوادم.',
  'Estimated distinct active visits reaching each ordered stage, including visits that started before this window.': 'تقدير للزيارات النشطة المختلفة التي بلغت كل مرحلة بالترتيب، بما فيها زيارات بدأت قبل هذه الفترة.',
  'Earlier steps truncated': 'لم تُحفظ الخطوات الأقدم',
  'The section order changed. Reload it before moving a section again.': 'تغير ترتيب الأقسام. أعد تحميله قبل تحريك قسم مجددًا.',
  'This place is not public or has no picture or video. Make it eligible before promoting it.': 'هذا المكان ليس عامًا أو ليس به صورة أو فيديو. استوفِ شروط أهليته قبل الترويج له.',
  'These dates overlap another booking or test. Choose another range or scope.': 'تتداخل المواعيد مع حجز أو اختبار آخر. اختر فترة أو نطاقًا آخر.',
  'This target is full for those dates. Choose another range or scope.': 'نطاق الاستهداف ممتلئ في هذه المواعيد. اختر فترة أو نطاقًا آخر.',
  'Every selected place must belong to this active subscriber. Reload the selection.': 'يجب أن يتبع كل مكان محدد هذا المشترك النشط. أعد تحميل الاختيار.',
  'Only an admin can make this change.': 'لا يستطيع إجراء هذا التغيير إلا مسؤول.',
  'Could not complete this action. Check the fields and try again.': 'تعذر إكمال الإجراء. راجع الحقول وحاول مجددًا.',
  'A reason is required for always-on promotion.': 'يجب إدخال سبب للترويج الدائم.',
  'A shuffle test shares unoccupied positions fairly to learn which places visitors act on; it is not a paid promotion.': 'يوزع اختبار التدوير الخانات الشاغرة بعدل لمعرفة الأماكن التي يتفاعل معها الزوار؛ وهو ليس ترويجًا مدفوعًا.',
  'Acted': 'تفاعل', 'Actual share': 'الحصة الفعلية', 'Add always-on promotion': 'إضافة ترويج دائم',
  'Additional ranked records are not included in the top 50': 'سجلات إضافية غير معروضة ضمن أول ٥٠ نتيجة',
  'Advertiser phone (optional)': 'هاتف المعلن (اختياري)',
  'Agreement amounts recorded this Cairo month, not cash received. Currencies are never added together.': 'مبالغ الاتفاقات الخارجية المسجلة في حجوزات هذا الشهر بتوقيت القاهرة، وليست أموالًا محصلة. لا تُجمع العملات المختلفة.',
  'The amount is recorded separately for each selected place.': 'يُسجَّل المبلغ لكل مكان مختار على حدة.',
  'All surfaces in the booking range': 'كل مواضع الظهور خلال فترة الحجز',
  'With free space': 'بها مساحة متاحة',
  'Paid reservations': 'حجوزات مدفوعة',
  'All eligible places': 'كل الأماكن المؤهلة', 'All states': 'كل الحالات', 'Amount per place': 'المبلغ لكل مكان',
  'Analytics filters missing': 'مرشحات التحليلات غير متاحة',
  'Anonymous visit numbers rotate at Cairo midnight. Duration is last activity minus first, not proof someone is still online. Only the latest 100 steps are retained.': 'تتغير أرقام الزيارات المجهولة عند منتصف الليل بتوقيت القاهرة. المدة هي الفرق بين أول نشاط وآخره، ولا تعني أن الزائر لا يزال متصلًا. تُحفظ أحدث ١٠٠ خطوة فقط.',
  'Area': 'المنطقة', 'Area list': 'قائمة المنطقة', 'City list': 'قائمة المدينة', 'Category list': 'قائمة التصنيف',
  'Home section': 'قسم الصفحة الرئيسية', 'Owner Plus plan': 'خطة المالك بلس', 'Organic': 'ظهور طبيعي',
  'Attributed delivery compared with the preceding range, plus selling opportunities and shuffle tests.': 'نتائج الظهور المنسوبة للترويج مقارنة بالفترة السابقة، مع فرص البيع واختبارات التدوير.',
  'Attributed promotion results': 'نتائج الترويج المنسوبة',
  'Availability is limited to 92 days per request. The backend validates the full booking when saving.': 'عرض الإتاحة محدود بـ٩٢ يومًا لكل طلب. يتحقق الخادم من الحجز كاملًا عند الحفظ.',
  'Back to campaigns': 'العودة للحملات', 'Back to results': 'العودة للنتائج', 'Booked and free per day': 'المحجوز والمتاح يوميًا',
  'Booking length': 'مدة الحجز', 'Booking range': 'فترة الحجز',
  'Bookings include paused reservations. Candidates are not simultaneous occupants; use the visitor preview for the exact current order.': 'تشمل الحجوزات الحملات الموقوفة مؤقتًا. المرشحون لا يظهرون جميعًا في الوقت نفسه؛ استخدم معاينة الزائر لمعرفة الترتيب الحالي بدقة.',
  'Browsed cities are not visitor locations. Visitors can appear in several groups; do not sum these estimates.': 'هذه المدن التي يتصفحها الزوار، وليست مواقعهم. قد يظهر الزائر في عدة مجموعات؛ لا تجمع هذه التقديرات.',
  'Busy areas and categories with nobody eligible for promotion in this period. Demand is counted place views, not unique visitors.': 'مناطق وتصنيفات نشطة بلا مكان مؤهل للترويج في هذه الفترة. الطلب هو مشاهدات الأماكن المحتسبة، وليس زوارًا فريدين.',
  'By place': 'حسب المكان', 'By source': 'حسب المصدر', 'Cairo time': 'توقيت القاهرة', 'Campaign recipient': 'المستفيد من الحملة',
  'Candidates overlapping the chosen dates': 'المرشحون المتداخلون مع الفترة المختارة', 'Capacity': 'السعة', 'Category browsed': 'تصفح تصنيفًا',
  'Choose 1 to 100 different places belonging to this subscriber.': 'اختر من مكان واحد إلى ١٠٠ مكان مختلف تابع لهذا المشترك.',
  'Choose 2 to 1000 different eligible places.': 'اختر من مكانين إلى ١٠٠٠ مكان مختلف مؤهل.',
  'Choose a complete surface and scope.': 'اختر موضع ظهور ونطاقًا كاملين.',
  'Choose a surface, choose an eligible place, agree the dates and amount, then compare what visitors did. Paid places are Sponsored; shuffle tests do not change earned ranking, loves or badges.': 'اختر موضع ظهور ومكانًا مؤهلًا، واتفق على المواعيد والمبلغ ثم قارن تفاعل الزوار. تحمل الأماكن المدفوعة علامة ممول؛ ولا تغير اختبارات التدوير الترتيب المكتسب أو الإعجابات أو الشارات.',
  'Choose a target.': 'اختر نطاق الاستهداف.',
  'Choose all Egypt, a city, its area, a category or a home section from the real surface catalogue.': 'اختر كل مصر أو مدينة أو منطقة داخلها أو تصنيفًا أو قسمًا رئيسيًا من قائمة مواضع الظهور الفعلية.',
  'Choose an ordered range of at most 366 days.': 'اختر فترة مرتبة لا تتجاوز ٣٦٦ يومًا.',
  'Choose an ordered range of at most 92 days.': 'اختر فترة مرتبة لا تتجاوز ٩٢ يومًا.',
  'Choose place': 'اختيار مكان', 'Choose places': 'اختيار الأماكن', 'Choose target': 'اختيار الاستهداف',
  'Choose the places, target, dates, advertiser and a valid amount; always-on also needs a reason.': 'اختر الأماكن والاستهداف والمواعيد والمعلن ومبلغًا صحيحًا؛ ويحتاج الترويج الدائم إلى سبب أيضًا.',
  'Choose where a visitor sees a place, see bookings and preview the actual cards.': 'اختر أين يرى الزائر المكان، وراجع الحجوزات وعاين البطاقات الفعلية.',
  'Choose who, where, when and the recorded agreement before saving.': 'حدد المستفيد وموضع الظهور والموعد والاتفاق المسجل قبل الحفظ.',
  'Cities being browsed': 'المدن الجاري تصفحها', 'City browsed': 'تصفح مدينة', 'Commercial kind': 'نوع القسم التجاري',
  'Comparison unavailable; prior minutes expired or were not observed.': 'المقارنة غير متاحة؛ انتهت مدة الاحتفاظ بالدقائق السابقة أو لم تُرصد.',
  'Could not export the complete report. No partial file was downloaded.': 'تعذر تصدير التقرير كاملًا. لم يُنزّل ملف جزئي.',
  'Could not load always-on promotions.': 'تعذر تحميل الترويج الدائم.', 'Could not load availability.': 'تعذر تحميل الإتاحة.',
  'Could not load homepage sections.': 'تعذر تحميل أقسام الصفحة الرئيسية.', 'Could not load more journeys.': 'تعذر تحميل زيارات إضافية.',
  'Could not load opportunities.': 'تعذر تحميل الفرص.', 'Could not load promotion results.': 'تعذر تحميل نتائج الترويج.',
  'Could not load shuffle results.': 'تعذر تحميل نتائج التدوير.', 'Could not load shuffle tests.': 'تعذر تحميل اختبارات التدوير.',
  'Could not load surfaces.': 'تعذر تحميل مواضع الظهور.', 'Could not load the visitor preview.': 'تعذر تحميل معاينة الزائر.',
  'Could not load this place’s promotions.': 'تعذر تحميل ترويج هذا المكان.', 'Could not open this subscription. Try again.': 'تعذر فتح هذا الاشتراك. حاول مجددًا.',
  'Could not search places.': 'تعذر البحث عن الأماكن.', 'Could not search subscribers.': 'تعذر البحث عن المشتركين.',
  'Create always-on promotion': 'إنشاء ترويج دائم', 'Create campaign': 'إنشاء حملة', 'Create shuffle test': 'إنشاء اختبار تدوير',
  'Current period': 'الفترة الحالية', 'Daily privacy salt missing': 'مفتاح الخصوصية اليومي غير متاح',
  'Directions tap': 'ضغط على الاتجاهات', 'Dimension contributions omitted': 'مساهمات أبعاد لم تُحتسب',
  'Disable section?': 'تعطيل القسم؟', 'Enable section?': 'تفعيل القسم؟',
  'Eligible places': 'الأماكن المؤهلة', 'Eligible promoted places today': 'أماكن مؤهلة للترويج اليوم',
  'Enter a test name.': 'أدخل اسم الاختبار.', 'Entry': 'بداية الزيارة', 'Every retained journey step': 'كل خطوات الزيارة المحفوظة',
  'Exact visitor preview': 'معاينة الزائر الفعلية', 'Expected share': 'الحصة المتوقعة', 'Expiry stays unchanged.': 'يبقى موعد الانتهاء دون تغيير.',
  'Export CSV': 'تصدير CSV', 'Exporting…': 'جارٍ التصدير…', 'For a subscriber': 'لمشترك', 'Free slots worth selling': 'خانات شاغرة تستحق البيع',
  'Has free space': 'به مساحة متاحة', 'Live funnel': 'مسار التفاعل المباشر', 'Live window': 'الفترة المباشرة',
  'Load more journeys': 'تحميل زيارات إضافية', 'Loved place': 'أعجب بمكان',
  'Manual totals are lifetime campaign counters; plan totals cover the report range. Do not add them as one period.': 'الإجماليات اليدوية تخص عمر الحملة كاملًا؛ وإجماليات الخطط تخص فترة التقرير. لا تجمعها كفترة واحدة.',
  'New shuffle test': 'اختبار تدوير جديد',
  'No always-on promotions yet. Create one with a reason, or review an Owner Plus subscription.': 'لا يوجد ترويج دائم بعد. أنشئ واحدًا مع سبب، أو راجع اشتراك المالك بلس.',
  'No end date': 'بلا موعد انتهاء', 'No end date. It stays eligible until you stop it.': 'بلا موعد انتهاء. يظل مؤهلًا حتى توقفه.',
  'No recorded exposure is a reason to investigate, not proof of no delivery. Missing and padded counters do not establish complete ingestion.': 'غياب الظهور المسجل يستدعي المراجعة ولا يثبت عدم الظهور. العدادات الناقصة أو المعبأة لا تثبت اكتمال جمع النشاط.',
  'No results': 'لا نتائج', 'No surfaces match these filters.': 'لا توجد مواضع ظهور تطابق المرشحات.', 'No target selected': 'لم يُحدد استهداف',
  'No tests on this page. Create a test to compare eligible places.': 'لا اختبارات في هذه الصفحة. أنشئ اختبارًا لمقارنة الأماكن المؤهلة.',
  'Nobody promoted': 'لا يوجد ترويج', 'Not serving': 'لا يظهر حاليًا', 'Notes (optional)': 'ملاحظات (اختياري)',
  'Observed accepted events only; visitors are an estimate. Visits count starts, not people still online.': 'الأحداث المرصودة والمقبولة فقط؛ عدد الزوار تقديري. الزيارات تحسب البدايات، وليس الأشخاص المتصلين الآن.',
  'Observed activity line; gaps are unknown. Faint line is yesterday when available.': 'خط النشاط المرصود؛ الفجوات مجهولة. الخط الخافت يمثل أمس عند توفره.',
  'Only attributed directions and saves are counted. Legacy zero counters do not prove complete ingestion. Current Cairo day is partial.': 'تُحتسب الاتجاهات والحفظ المنسوبان للترويج فقط. العدادات القديمة الصفرية لا تثبت اكتمال الرصد. يوم القاهرة الحالي غير مكتمل.',
  'Open every retained step': 'فتح كل الخطوات المحفوظة', 'Opportunities': 'الفرص', 'Opportunity demand period': 'فترة رصد الطلب على الفرص',
  'Page viewed': 'شاهد صفحة', 'Pages viewed': 'صفحات تمت مشاهدتها', 'Paid': 'مدفوع', 'Paid agreements with no recorded shows': 'اتفاقات مدفوعة بلا ظهور مسجل',
  'Paid campaigns come first, then plans; shuffle fills only unoccupied positions. Low exposure is not proof that a place is worse.': 'الحملات المدفوعة أولًا ثم الخطط؛ ويملأ التدوير الخانات الشاغرة فقط. قلة الظهور لا تثبت ضعف المكان.',
  'Place opened': 'فتح مكانًا', 'Places belonging to': 'أماكن تابعة لـ', 'Plan promotion is enabled.': 'ترويج الخطط مفعل.',
  'Plan promotion is switched off; subscriptions do not serve promotions.': 'ترويج الخطط معطل؛ لا تقدم الاشتراكات ترويجًا حاليًا.',
  'Preview plan change': 'معاينة تغيير الخطة',
  'Preview the server-computed difference before confirming. No payment or refund is recorded by this action.': 'عاين الفرق الذي يحسبه الخادم قبل التأكيد. لا يسجل هذا الإجراء دفعًا أو استردادًا.',
  'Previous period': 'الفترة السابقة', 'Promotion occupancy': 'إشغال الترويج',
  'Promotion saved. The backend checks eligibility before serving.': 'حُفظ الترويج. يتحقق الخادم من الأهلية قبل عرضه.',
  'Promotion-specific metrics unavailable': 'مقاييس هذا الترويج غير متاحة', 'Ranked shuffle results': 'نتائج التدوير مرتبة',
  'Rate from previous step': 'النسبة من الخطوة السابقة', 'Reason (required)': 'السبب (مطلوب)', 'Recent journeys': 'الزيارات الأخيرة',
  'Recorded agreement': 'الاتفاق المسجل', 'Recorded agreements this month': 'اتفاقات مسجلة هذا الشهر',
  'Refresh live activity': 'تحديث النشاط المباشر', 'Refresh preview': 'تحديث المعاينة', 'Reload the section order.': 'أعد تحميل ترتيب الأقسام.',
  'Remove from test': 'إزالة من الاختبار', 'Results sections': 'أقسام النتائج', 'Review the recorded agreement before saving.': 'راجع الاتفاق المسجل قبل الحفظ.',
  'Right now': 'الآن', 'Same window yesterday': 'نفس الفترة أمس', 'Save campaign': 'حفظ الحملة', 'Saved place': 'حفظ مكانًا',
  'Saved. Live on the website now.': 'تم الحفظ. يظهر على الموقع الآن.',
  'Search filters the current server page. Use the pager to inspect other pages.': 'البحث يرشح صفحة الخادم الحالية. استخدم أزرار الصفحات لمراجعة الصفحات الأخرى.',
  'Search in progress (not counted)': 'بحث جارٍ (غير محتسب)', 'Search query (optional)': 'عبارة البحث (اختياري)', 'Search result opened': 'فتح نتيجة بحث',
  'Searched or browsed a city': 'بحث أو تصفح مدينة', 'Selected': 'المحدد', 'Selected target': 'الاستهداف المحدد',
  'Share unoccupied positions to compare eligible places, without marking them Sponsored.': 'وزع الخانات الشاغرة لمقارنة الأماكن المؤهلة، دون وضع علامة ممول عليها.',
  'Shared place': 'شارك مكانًا', 'Shuffle members': 'الأماكن المشاركة في التدوير', 'Shuffle test created.': 'تم إنشاء اختبار التدوير.', 'Shuffle tests': 'اختبارات التدوير',
  'Some activity was not counted: Redis was busy.': 'لم يُحتسب بعض النشاط: كان Redis مشغولًا.',
  'Some activity was not counted.': 'لم يُحتسب بعض النشاط.', 'Some journey steps were lost': 'فُقدت بعض خطوات الزيارة',
  'Some minutes are unknown. Lines break at gaps; missing activity is never zero.': 'بعض الدقائق مجهولة. تنقطع الخطوط عند الفجوات؛ النشاط المفقود لا يُعرض صفرًا.',
  'Space available': 'مساحة متاحة', 'Start a campaign here': 'بدء حملة هنا', 'Started at': 'بدأت في',
  'Stop always-on promotion?': 'إيقاف الترويج الدائم؟', 'Stop shuffle test': 'إيقاف اختبار التدوير', 'Stop shuffle test?': 'إيقاف اختبار التدوير؟',
  'Surface': 'موضع الظهور', 'Surface and scope': 'موضع الظهور والنطاق', 'Surfaces grouped by kind and city': 'مواضع الظهور حسب النوع والمدينة',
  'Tap': 'ضغطة', 'Test and target': 'الاختبار والاستهداف', 'Test name': 'اسم الاختبار',
  'The backend snapshots 2 to 1000 matching public places at creation. Later places do not join the test.': 'يحفظ الخادم من مكانين إلى ١٠٠٠ مكان عام مطابق عند الإنشاء. لا تنضم الأماكن اللاحقة للاختبار.',
  'The owner changed. Open this place to review its current subscriber.': 'تغير المالك. افتح المكان لمراجعة المشترك الحالي.',
  'The selected window applies to every live block. Short windows refresh every 5 seconds, longer ones every minute; refresh pauses while this tab is hidden.': 'تطبق الفترة المختارة على كل أجزاء النشاط المباشر. تتحدث الفترات القصيرة كل ٥ ثوانٍ والطويلة كل دقيقة؛ ويتوقف التحديث عندما تكون الصفحة مخفية.',
  'The target cannot change after the campaign starts.': 'لا يمكن تغيير الاستهداف بعد بدء الحملة.',
  'This changes whether the section appears to visitors.': 'يغير هذا ظهور القسم للزوار.',
  'This is an offline agreement, not cash received. One campaign is created for each selected place, or none if any place is refused.': 'هذا اتفاق خارجي وليس أموالًا محصلة. تُنشأ حملة لكل مكان محدد، أو لا تُنشأ أي حملة إذا رُفض أي مكان.',
  'This journey expired or could not be read. Refresh the feed and choose a current visit.': 'انتهت مدة هذه الزيارة أو تعذر قراءتها. حدث القائمة واختر زيارة حالية.',
  'This permanently ends this promotion. It cannot be resumed. The place, recorded agreement and delivery history remain.': 'ينهي هذا الترويج نهائيًا ولا يمكن استئنافه. يبقى المكان والاتفاق المسجل وسجل الظهور.',
  'This permanently removes the section and its pins. Its section campaigns are removed too. The places remain.': 'يحذف هذا القسم وتثبيتاته نهائيًا، وكذلك حملاته الخاصة. تبقى الأماكن.',
  'This permanently stops rotation for this test. It cannot be resumed; accepted results remain.': 'يوقف هذا التدوير للاختبار نهائيًا ولا يمكن استئنافه؛ تبقى النتائج المقبولة.',
  'This preview made no changes. Confirm to apply it.': 'لم تُجرِ هذه المعاينة أي تغيير. أكد لتطبيقه.',
  'This report describes eligibility and accepted delivery, not a visitor-specific card order. Use Where ads appear for the exact preview.': 'يوضح هذا التقرير الأهلية والظهور المقبول، وليس ترتيب البطاقات لزائر بعينه. استخدم مواضع ظهور الإعلانات للمعاينة الدقيقة.',
  'Today · Cairo time': 'اليوم · توقيت القاهرة', 'Too small to compare': 'العينة أصغر من أن تُقارن', 'Top pages': 'أكثر الصفحات', 'Top places': 'أكثر الأماكن',
  'Total recorded agreement': 'إجمالي الاتفاق المسجل', 'Unique visitors (estimate)': 'زوار فريدون (تقدير)',
  'Unknown': 'غير معروف', 'Unknown visitors': 'عدد الزوار غير معروف', 'Unknown step': 'خطوة غير معروفة', 'Updated': 'تم التحديث',
  'View ranked results': 'عرض النتائج المرتبة', 'View report': 'عرض التقرير', 'View subscription': 'عرض الاشتراك', 'View surface': 'عرض موضع الظهور',
  'Visit': 'زيارة', 'Visits': 'الزيارات', 'Visits started': 'زيارات بدأت', 'Waiting for the first live snapshot.': 'بانتظار أول قراءة للنشاط المباشر.',
  'Website or app': 'الموقع أو التطبيق', 'What they searched': 'ما الذي بحثوا عنه',
  'booked': 'محجوز', 'cards': 'بطاقات', 'counted events': 'أحداث محتسبة', 'counted place views': 'مشاهدات أماكن محتسبة',
  'estimated visitors': 'زوار تقديريًا', 'free': 'متاح', 'maximum free positions in the next 7 days': 'أقصى خانات متاحة خلال الأيام السبعة المقبلة',
  'paid positions': 'خانات مدفوعة', 'per place': 'لكل مكان', 'recorded agreements': 'اتفاقات مسجلة', 'result clicks': 'ضغطات على النتائج',
  'seconds': 'ثوانٍ', 'seconds ago': 'ثوانٍ مضت', 'settled searches': 'عمليات بحث مكتملة', 'visits': 'زيارات',
  '1 minute': 'دقيقة واحدة', '5 minutes': '٥ دقائق', '15 minutes': '١٥ دقيقة', '30 minutes': '٣٠ دقيقة',
  '1 hour': 'ساعة واحدة', '3 hours': '٣ ساعات', '6 hours': '٦ ساعات', '12 hours': '١٢ ساعة', '24 hours': '٢٤ ساعة',
};
