export const analyticsCopy: Record<string, string> = {
  'Enabled': 'مفعّل',
  'Keyword saved': 'تم حفظ الكلمة المفتاحية',
  'Assignment saved': 'تم حفظ التعيين',
  'Decision undone': 'تم التراجع عن القرار',
  'No change': 'بدون تغيير',
  'No cities found.': 'لا توجد مدن.',
  'Overview': 'نظرة عامة',
  'From': 'من',
  'To': 'إلى',
  'All cities': 'كل المدن',
  'Could not load cities.': 'تعذر تحميل المدن.',
  'Could not load places.': 'تعذر تحميل الأماكن.',
  'All categories': 'كل التصنيفات',
  'Name (Arabic)': 'الاسم بالعربية',
  'All statuses': 'كل الحالات',
  'Visible': 'ظاهر',
  'Hidden': 'مخفي',
  'Unspecified city': 'مدينة غير محددة',
  'All roles': 'كل الأدوار',
  'Session trend for the selected period': 'تغير الجلسات خلال الفترة المختارة',
  'Analytics': 'التحليلات',
  'Analytics sections': 'أقسام التحليلات',
  'Analytics period': 'فترة التحليلات',
  'Search and movement, measured in Cairo calendar days.': 'البحث والتنقل، بحسب أيام التقويم بتوقيت القاهرة.',
  'Search terms': 'كلمات البحث',
  'Missing words': 'كلمات مفقودة',
  'Movement': 'التنقل',
  'Keywords': 'الكلمات المفتاحية',
  'Keyword': 'الكلمة المفتاحية',
  'Last 90 days': 'آخر ٩٠ يومًا',
  'Custom range': 'فترة مخصصة',
  'All platforms': 'كل المنصات',
  'Unknown platform': 'منصة غير معروفة',
  'App': 'التطبيق',
  'Web': 'الموقع',
  'Cairo · inclusive dates': 'القاهرة · تشمل تاريخي البداية والنهاية',
  'Choose an ordered range of at most 401 days.': 'اختر فترة مرتبة لا تتجاوز ٤٠١ يومًا.',
  'Search records': 'ابحث في السجلات',
  'No matching records.': 'لا توجد سجلات مطابقة. غيّر البحث أو المرشحات.',
  'All surfaces': 'كل مواضع العرض',
  'All sections': 'كل الأقسام',
  'All delivery': 'كل حالات الظهور',
  'With shows': 'ظهر للزوار',
  'Without shows': 'لم يظهر للزوار',
  'All promotion types': 'كل أنواع الترويج',
  'All promotion sources': 'كل مصادر الترويج',
  'Unreadable reports': 'تقارير تعذر قراءتها',
  'Could not load analytics.': 'تعذر تحميل التحليلات.',
  'Sessions': 'جلسات',
  'sessions · selected period': 'جلسات · الفترة المختارة',
  'Recorded searches': 'عمليات البحث المسجلة',
  'searches · selected period': 'عمليات بحث · الفترة المختارة',
  'Nothing found share': 'نسبة البحث دون نتائج',
  'of recorded searches · selected period': 'من البحث المسجل · الفترة المختارة',
  'Result taps': 'نقرات النتائج',
  'Recorded terms exclude private text and very short searches. Taps are events, not unique people.': 'الكلمات المسجلة لا تشمل النصوص الخاصة والبحث القصير جدًا. النقرات أحداث وليست أشخاصًا مختلفين.',
  'Sessions by day': 'الجلسات يوميًا',
  'Only stored session days are shown; missing days are not invented.': 'تُعرض أيام الجلسات المسجلة فقط؛ لا نضيف أيامًا غير مسجلة.',
  'Trend compares searches with the previous equal-length period. Taps can exceed searches.': 'يقارن التغير عمليات البحث بالفترة السابقة المساوية في الطول. قد تتجاوز النقرات عمليات البحث.',
  'Could not load search terms.': 'تعذر تحميل كلمات البحث.',
  'Sort search terms': 'ترتيب كلمات البحث',
  'Most searches': 'الأكثر بحثًا',
  'Most empty searches': 'الأكثر دون نتائج',
  'Fewest taps per search': 'الأقل نقرًا لكل بحث',
  'No owning keyword': 'لا توجد كلمة مفتاحية مالكة',
  'Searches': 'عمليات بحث',
  'Nothing found': 'دون نتائج',
  'Taps per search': 'نقرات لكل بحث',
  'Trend': 'التغير',
  'No previous searches': 'لا توجد عمليات بحث سابقة',
  'Actions in sessions': 'أفعال داخل الجلسات',
  'These are sessions containing actions, not an ordered conversion funnel. City is the first known city of the session.': 'هذه جلسات تضم أفعالًا وليست مسار تحويل مرتبًا. المدينة هي أول مدينة معروفة في الجلسة.',
  'A visit ends after 30 minutes without activity.': 'تنتهي الزيارة بعد ٣٠ دقيقة دون نشاط.',
  'Searched': 'بحثوا',
  'Sessions with a search, divided by all sessions.': 'الجلسات التي تضم بحثًا مقسومة على كل الجلسات.',
  'Opened a place': 'فتحوا مكانًا',
  'Sessions with a place view, divided by all sessions.': 'الجلسات التي تضم فتح مكان مقسومة على كل الجلسات.',
  'Acted after opening': 'تفاعلوا بعد الفتح',
  'Sessions acting on a previously opened place, divided by sessions with a place view.': 'الجلسات التي تفاعلت مع مكان مفتوح سابقًا مقسومة على الجلسات التي فتحت مكانًا.',
  'Session-place pairs': 'أزواج الجلسة والمكان',
  'Each place counts once per session, not once per page load.': 'يُحسب المكان مرة لكل جلسة وليس لكل تحميل صفحة.',
  'Pairs with an action': 'أزواج تضم تفاعلًا',
  'Previously viewed session-place pairs with an action, divided by viewed pairs.': 'أزواج الجلسة والمكان المفتوحة سابقًا التي تضم تفاعلًا مقسومة على الأزواج المفتوحة.',
  'in selected period': 'في الفترة المختارة',
  'Entries': 'بدايات الزيارات',
  'Exits': 'نهايات الزيارات',
  'The first recorded screen of each session.': 'أول شاشة مسجلة في كل جلسة.',
  'The last recorded screen of each session.': 'آخر شاشة مسجلة في كل جلسة.',
  'Commonest steps': 'الخطوات الأكثر شيوعًا',
  'Consecutive recorded screens; overflow is folded into other, so this is approximate.': 'شاشات مسجلة متتالية؛ تُجمع الزيادة تحت «أخرى»، لذا الأرقام تقريبية.',
  'steps · selected period': 'خطوات · الفترة المختارة',
  'Could not load movement.': 'تعذر تحميل التنقل.',
  'Lost searches are a prioritization estimate, not a count of failed sessions. Suggestions never assign a keyword automatically.': 'البحث المفقود تقدير لترتيب الأولويات وليس عدد الجلسات الفاشلة. الاقتراحات لا تعيّن كلمة مفتاحية تلقائيًا.',
  'Read only: viewers cannot change keywords or decisions.': 'للقراءة فقط: لا يمكن للمشاهدين تغيير الكلمات المفتاحية أو القرارات.',
  'This term changed or belongs to another keyword. Refresh and review it before trying again.': 'تغيرت الكلمة أو تنتمي إلى كلمة مفتاحية أخرى. حدّث وراجعها قبل المحاولة مجددًا.',
  'Could not save this word decision. Your choice is kept.': 'تعذر حفظ قرار الكلمة. احتفظنا باختيارك.',
  'Recent decisions': 'القرارات الأخيرة',
  'Undo decision': 'تراجع عن القرار',
  'Could not load missing words.': 'تعذر تحميل الكلمات المفقودة.',
  'lost searches · selected period': 'عمليات بحث مفقودة · الفترة المختارة',
  'Suggested keywords': 'كلمات مفتاحية مقترحة',
  'Make it a spelling of…': 'اجعلها تهجئة لـ…',
  'Ignore word': 'تجاهل الكلمة',
  'Could not load keywords.': 'تعذر تحميل الكلمات المفتاحية.',
  'Choose keyword': 'اختر كلمة مفتاحية',
  'Save spelling': 'حفظ التهجئة',
  'Could not load term details.': 'تعذر تحميل تفاصيل كلمة البحث.',
  'Could not undo this decision. Refresh and try again.': 'تعذر التراجع عن القرار. حدّث وحاول مجددًا.',
  'Owning keyword': 'الكلمة المفتاحية المالكة',
  'Ignored word': 'كلمة متجاهلة',
  'Spelling saved': 'تم حفظ التهجئة',
  'Daily search series': 'البحث يوميًا',
  'Tapped places': 'الأماكن المنقورة',
  'Would match now': 'أماكن تطابق الآن',
  'Current public search matches, not a reconstruction of past results.': 'نتائج البحث العامة الحالية، وليست إعادة بناء للنتائج السابقة.',
  'Unknown record': 'سجل غير معروف',
  'Cuisine': 'نوع المأكولات',
  'Vibe': 'الأجواء',
  'Occasion': 'المناسبة',
  'Activity': 'النشاط',
  'Audience': 'الجمهور',
  'Feature': 'الميزة',
  'Price': 'السعر',
  'Other': 'أخرى',
  'Use up to 30 spellings, each between 1 and 40 characters.': 'استخدم حتى ٣٠ تهجئة، طول كل منها بين حرف و٤٠ حرفًا.',
  'This spelling is already included.': 'هذه التهجئة موجودة بالفعل.',
  'Check names and notes, and add or clear the pending spelling.': 'راجع الأسماء والملاحظات، وأضف التهجئة المعلقة أو امسحها.',
  'A name or spelling belongs to another keyword. Review the names and spellings.': 'اسم أو تهجئة ينتمي إلى كلمة مفتاحية أخرى. راجع الأسماء والتهجئات.',
  'Could not save keyword. Your edits are kept.': 'تعذر حفظ الكلمة المفتاحية. احتفظنا بتعديلاتك.',
  'Name (English) — optional': 'الاسم بالإنجليزية — اختياري',
  'Keyword group': 'مجموعة الكلمة المفتاحية',
  'Spellings': 'التهجئات',
  'Add spelling': 'إضافة تهجئة',
  'Remove spelling': 'إزالة التهجئة',
  'Spellings are hidden search words, not public labels.': 'التهجئات كلمات بحث مخفية وليست وسومًا عامة.',
  'Internal notes — optional': 'ملاحظات داخلية — اختيارية',
  'Saved, but could not refresh. Reload before changing anything else.': 'تم الحفظ لكن تعذر التحديث. أعد التحميل قبل تغيير أي شيء آخر.',
  'Save keyword': 'حفظ الكلمة المفتاحية',
  'Create keyword': 'إنشاء كلمة مفتاحية',
  'Keywords and place assignments are current team configuration, not period statistics.': 'الكلمات المفتاحية وتعيين الأماكن إعدادات الفريق الحالية وليست إحصاءات الفترة.',
  'All keyword groups': 'كل مجموعات الكلمات المفتاحية',
  'assigned places · now': 'أماكن معيّنة · الآن',
  'Could not load keyword.': 'تعذر تحميل الكلمة المفتاحية.',
  'Keyword details': 'تفاصيل الكلمة المفتاحية',
  'Assigned places': 'الأماكن المعيّنة',
  'All place statuses': 'كل حالات الأماكن',
  'Assign keyword to places': 'تعيين الكلمة المفتاحية لأماكن',
  'Preview first. Applying changes only this keyword and preserves other keywords.': 'عاين أولًا. التطبيق يغير هذه الكلمة المفتاحية فقط ويحافظ على الكلمات الأخرى.',
  'Assignment method': 'طريقة التعيين',
  'Assignment action': 'إجراء التعيين',
  'Pick places': 'اختر أماكن',
  'Use a selector': 'استخدم مرشّح اختيار',
  'Add keyword': 'إضافة الكلمة المفتاحية',
  'Remove keyword': 'إزالة الكلمة المفتاحية',
  'Select place': 'اختر المكان',
  'places selected': 'أماكن مختارة',
  'Remove selection': 'إزالة الاختيار',
  'Area key — optional': 'مفتاح المنطقة — اختياري',
  'Place name search — optional': 'البحث باسم المكان — اختياري',
  'Selectors combine with AND. Area is an exact key; search matches place names only. Draft places can be assigned.': 'تُجمع المرشحات معًا. المنطقة مفتاح مطابق تمامًا؛ البحث يطابق أسماء الأماكن فقط. يمكن تعيين الأماكن المسودة.',
  'I intend to select all non-deleted, unmerged places.': 'أقصد اختيار كل الأماكن غير المحذوفة وغير المدمجة.',
  'Could not load selector options.': 'تعذر تحميل خيارات مرشّح الاختيار.',
  'The selection changed. Preview again and review the new digest before applying.': 'تغير الاختيار. عاين مجددًا وراجع البصمة الجديدة قبل التطبيق.',
  'Narrow the selection or remove merged places, then preview again.': 'ضيّق الاختيار أو أزل الأماكن المدمجة، ثم عاين مجددًا.',
  'Could not update keyword assignments. Your selection is kept.': 'تعذر تحديث تعيينات الكلمة المفتاحية. احتفظنا باختيارك.',
  'Working…': 'جارٍ العمل…',
  'Preview assignment': 'معاينة التعيين',
  'Review assignment': 'مراجعة التعيين',
  'links added': 'روابط مضافة',
  'links removed': 'روابط محذوفة',
  'Plan digest': 'بصمة المعاينة',
  'Apply reviewed assignment': 'تطبيق التعيين الذي راجعته',
};
