export const dashboardCopy: Record<string, string> = {
  'Check the week below before saving — pasted text is a starting point, not a source of truth.': 'راجع الأسبوع أدناه قبل الحفظ؛ النص الملصق نقطة بداية وليس مصدراً مؤكداً.',
  'Or set specific days': 'أو حدد أياماً بعينها', 'This week': 'هذا الأسبوع', 'places': 'أماكن',
  'No cities yet.': 'لا توجد مدن بعد.', 'No places have an area set yet.': 'لا توجد أماكن محددة المنطقة بعد.',
  'Booked capacity across national and city placements.': 'السعة المحجوزة للمواضع العامة ومواضع المدن.',
  'Report not found.': 'لم يتم العثور على التقرير.',
  'Ad inventory': 'السعة الإعلانية', 'Edit campaign': 'تعديل الحملة', 'Loading booking details…': 'جارٍ تحميل بيانات الحجز…',
  'Review and update a booked placement.': 'مراجعة موضع إعلان محجوز وتحديثه.',
  'Update the booking record and advertiser details.': 'تحديث بيانات الحجز والمعلن.',
  'Book a Featured or Top 10 placement for an active place.': 'حجز إعلان مميز أو ضمن أفضل ١٠ لمكان نشط.',
  'Manage booked placements, serving state, advertiser records and performance.': 'إدارة المواضع المحجوزة وحالة العرض وبيانات المعلنين والأداء.',
  'Inspect the earned ranking, sponsored slots and current fair-rotation queue.': 'معاينة ترتيب الأماكن والمواضع الممولة وقائمة التناوب العادل الحالية.',
  'Top 10 city': 'مدينة أفضل ١٠', 'Leave as All Egypt for the national list.': 'اتركها على كل مصر للقائمة العامة.',
  'Start date': 'تاريخ البداية', 'End date': 'تاريخ النهاية', 'Calendar dates are inclusive in Africa/Cairo.': 'تواريخ البداية والنهاية مشمولة بتوقيت القاهرة.',
  'Advertiser name': 'اسم المعلن', 'Advertiser phone': 'هاتف المعلن', 'Optional; stored for the admin team only.': 'اختياري؛ يحفظ لفريق الإدارة فقط.',
  'Amount paid': 'المبلغ المدفوع', 'Currency': 'العملة', 'Notes': 'ملاحظات', 'Optional internal notes; maximum 2,000 characters.': 'ملاحظات داخلية اختيارية؛ حتى ٢٠٠٠ حرف.',
  'Live places': 'الأماكن المنشورة', 'Areas': 'المناطق', 'Drafts': 'المسودات', 'Across all cities': 'في كل المدن', 'Not visible to visitors': 'غير ظاهرة للزوار',
  'Free': 'متاح', 'Partly sold': 'محجوز جزئياً', 'Full': 'مكتمل', 'Oversold': 'تجاوز السعة',
  'Previous 4 weeks': 'الأسابيع الأربعة السابقة', 'Next 4 weeks': 'الأسابيع الأربعة التالية',
  'Resume': 'استئناف', 'Pause': 'إيقاف مؤقت', 'End': 'إنهاء',
  'Give AI assistants scoped access. Create, copy once, and revoke your own keys.': 'منح المساعدين صلاحيات محددة. أنشئ مفاتيحك وانسخها مرة واحدة أو ألغها.',
  'Rotate your password. Other signed-in sessions will be revoked on the next refresh.': 'تغيير كلمة المرور. تنتهي الجلسات الأخرى عند التحديث التالي.',
  'Back to settings': 'العودة للإعدادات',
  'Search places...': 'ابحث عن الأماكن…', 'Search categories...': 'ابحث عن التصنيفات…', 'Search cities...': 'ابحث عن المدن…',
  'Search tags...': 'ابحث عن الوسوم…', 'Search amenities...': 'ابحث عن المرافق…', 'Search admins...': 'ابحث عن المسؤولين…',
  'Search region': 'البحث عن منطقة', 'Filter by city': 'التصفية حسب المدينة', 'Search area — zamalek, nasr city, naama bay, الزمالك…': 'ابحث عن منطقة — الزمالك، مدينة نصر، خليج نعمة…',
  '← Settings': 'الإعدادات →', 'Connect AI assistants without sharing your admin password.': 'ربط مساعدي الذكاء الاصطناعي دون مشاركة كلمة مرورك.',
  'Create key': 'إنشاء مفتاح', 'Permissions remain capped by each owner&apos;s current role; disabling an owner disables their keys.': 'تظل الصلاحيات ضمن دور صاحب المفتاح الحالي؛ تعطيل صاحبه يعطل مفاتيحه.',
  'Could not verify your role.': 'تعذر التحقق من دورك.', 'Retry session': 'إعادة التحقق من الجلسة',
  'Could not load keys. Check your session and use Refresh to retry.': 'تعذر تحميل المفاتيح. تحقق من جلستك ثم استخدم التحديث للمحاولة مجدداً.',
  'Owner:': 'الصاحب:', '· 25 per page. Revoked keys stay visible.': '· ٢٥ في الصفحة. تظل المفاتيح الملغاة ظاهرة.',
  'will immediately lose access.': 'سيفقد الوصول فوراً.', 'The credential cannot be reactivated; its owner can create a replacement.': 'لا يمكن إعادة تفعيل المفتاح؛ يستطيع صاحبه إنشاء بديل.',
  'Give an AI assistant access within your own admin role. Keys cannot manage accounts, log in or create other keys.': 'امنح مساعداً صلاحيات ضمن دورك الإداري. لا يمكن للمفاتيح إدارة الحسابات أو تسجيل الدخول أو إنشاء مفاتيح أخرى.',
  'Viewers can create read-only keys. Editing and deleting require an admin role.': 'يمكن للمشاهدين إنشاء مفاتيح للقراءة فقط. يتطلب التعديل والحذف دور مسؤول.',
  'Deletion can permanently remove media files. Give delete permission only when necessary. Closing while creation is in progress can leave a key you must revoke and recreate.': 'قد يحذف الإجراء ملفات الوسائط نهائياً. امنح صلاحية الحذف عند الضرورة فقط. إغلاق النافذة أثناء الإنشاء قد يترك مفتاحاً عليك إلغاؤه وإنشاء بديل له.',
  'MCP entrypoint on the AI&apos;s computer': 'مسار تشغيل MCP على جهاز المساعد', 'API base URL (including /v1)': 'رابط API الأساسي (شاملاً /v1)',
  'Enter an absolute index.mjs path and an HTTPS API base URL ending in /v1 to enable Copy config. Never put the key in either field.': 'أدخل مسار index.mjs كاملاً ورابط API آمناً ينتهي بـ /v1 لتفعيل نسخ الإعدادات. لا تضع المفتاح في أي من الحقلين.',
  'Requires Node 22+ and the backend repository&apos;s mcp folder on the AI&apos;s computer. Replace the path before copying. Never commit this configuration or share it in chat. ZadLoop&apos;s import format is not independently verified; use its command, args and environment fields if JSON import is unavailable.': 'يتطلب Node 22 أو أحدث ومجلد mcp من مشروع الخادم على جهاز المساعد. استبدل المسار قبل النسخ. لا تحفظ الإعدادات في المستودع ولا تشاركها في المحادثات. صيغة استيراد ZadLoop غير مؤكدة؛ استخدم حقول الأمر والوسائط والبيئة إذا لم يتوفر استيراد JSON.',
  'For local-file uploads, add KHARGNY_UPLOAD_ROOT to the client&apos;s environment with one absolute local upload folder. Local uploads are disabled without it; URL uploads still work. See mcp/README.md for the exact field to add.': 'لرفع ملفات محلية، أضف KHARGNY_UPLOAD_ROOT إلى بيئة العميل بمسار كامل لمجلد رفع محلي واحد. الرفع المحلي معطل بدونه؛ يظل الرفع بالرابط متاحاً. راجع mcp/README.md للحقل المطلوب.',
  'Pick a strong password. Other browsers signed in with this account will be signed out on the next refresh.': 'اختر كلمة مرور قوية. تنتهي جلسات الحساب على المتصفحات الأخرى عند التحديث التالي.',
  'Reset all content': 'إعادة ضبط كل المحتوى', 'Reset all content…': 'إعادة ضبط كل المحتوى…', 'Delete all content?': 'حذف كل المحتوى؟',
  'Permanently deletes every place, city, category, amenity, tag and uploaded photo or video — a clean slate. Admin accounts, sign-ins and the audit log are kept. This cannot be undone and no backup is taken.': 'يحذف نهائياً كل الأماكن والمدن والتصنيفات والمرافق والوسوم والصور والفيديوهات المرفوعة. تبقى حسابات المسؤولين وجلساتهم وسجل التدقيق. لا يمكن التراجع ولا تؤخذ نسخة احتياطية.',
  'This is irreversible. Everything listed below is destroyed, including the files in storage.': 'لا يمكن التراجع. يحذف كل ما هو موضح أدناه، بما فيه الملفات المخزنة.',
  'Checking what would be deleted…': 'جارٍ التحقق مما سيحذف…', 'There is no content to delete — everything is already empty.': 'لا يوجد محتوى للحذف؛ كل الأقسام فارغة بالفعل.',
  'files in storage': 'ملفات مخزنة', 'Kept:': 'يبقى:', 'Type': 'اكتب', 'to confirm': 'للتأكيد',
  'Places in “': 'الأماكن في «', 'Search the catalog to add places, drag order with the arrows, and save. This section shows exactly these places, in this order, on the homepage and app.': 'ابحث في الدليل لإضافة أماكن ورتبها بالأسهم ثم احفظ. يعرض هذا القسم هذه الأماكن بهذا الترتيب في الصفحة الرئيسية والتطبيق.',
  'Added': 'تمت الإضافة', 'In this section (': 'في هذا القسم (', 'Loading…': 'جارٍ التحميل…', 'No places yet — search above to add some.': 'لا توجد أماكن بعد؛ ابحث أعلاه لإضافتها.', 'Save places': 'حفظ الأماكن',
  'Ad campaigns': 'الحملات الإعلانية', 'Ads inventory': 'السعة الإعلانية',
  'View and manage booked sponsored placements.': 'عرض مواضع الإعلانات الممولة المحجوزة وإدارتها.',
  'The place&apos;s photo gallery — pick several at once or drag &amp; drop them in. Drag a photo (or use the arrows) to set the order they appear in the public carousel. The first photo is this place&apos;s cover (list thumbnail + detail hero); use &ldquo;Set cover&rdquo; to promote another one. Separate from a city&apos;s own cover photo, which lives in the Cities tab.': 'معرض صور المكان؛ اختر عدة صور أو اسحبها وأفلتها. اسحب صورة أو استخدم الأسهم لترتيبها في المعرض العام. الصورة الأولى غلاف المكان في القائمة وصفحة التفاصيل؛ استخدم «تعيين كغلاف» لاختيار أخرى. غلاف المدينة مستقل ويعدل في تبويب المدن.',
  ': full control.': ': جميع الصلاحيات.', ': content management.': ': إدارة المحتوى.', ': read-only.': ': عرض فقط.',
  'The account is removed from this list, its sessions end immediately and its email becomes available again. What they did stays in the audit log. This cannot be undone — use Disable instead if you may want them back.': 'يحذف الحساب من القائمة وتنتهي جلساته فوراً ويصبح بريده متاحاً مجدداً. تبقى إجراءاته في سجل التدقيق. لا يمكن التراجع؛ استخدم التعطيل إذا كنت تريد إعادته لاحقاً.',
  'The admin will be marked inactive and signed out within one request. They won&apos;t be able to log in again until you re-enable them.': 'يعطل حساب المسؤول وتنتهي جلسته خلال طلب واحد. لن يتمكن من الدخول حتى تعيد تفعيله.',
  'The admin will be able to sign in again immediately.': 'سيتمكن المسؤول من تسجيل الدخول فوراً.',
  'Set to &quot;Disabled&quot; to revoke this admin&apos;s access. Use the Disable action on the list page for the recommended flow (it also handles the sign-out side effect).': 'اختر «معطل» لإلغاء وصول المسؤول. يفضل استخدام إجراء التعطيل في صفحة القائمة لأنه ينهي الجلسات أيضاً.',
  'Showing campaigns linked from an inventory scope or day.': 'عرض الحملات المرتبطة بنطاق سعة أو يوم.',
  'Ranked by rating, saves, directions and views. Sponsored rows replace the rank number.': 'الترتيب حسب التقييم والحفظ وطلبات الاتجاهات والمشاهدات. تحل علامة التمويل محل رقم الترتيب للحملات الممولة.',
  'No ranking candidates for this scope.': 'لا توجد أماكن مؤهلة للترتيب في هذا النطاق.',
  'All live Top 10 campaigns for this scope. “Shown now” reflects the current 10-minute bucket.': 'كل حملات أفضل ١٠ المباشرة في هذا النطاق. «معروض الآن» يعكس فترة التناوب الحالية ومدتها ١٠ دقائق.',
  'No live sponsored campaigns in this scope.': 'لا توجد حملات ممولة مباشرة في هذا النطاق.',
  'Khargny · خرجني — Sponsored placement report': 'خرجني — تقرير موضع الإعلان الممول',
  'Placement:': 'موضع الإعلان:', 'Scope:': 'النطاق:', 'Dates:': 'التواريخ:', 'Timezone:': 'المنطقة الزمنية:',
  'Daily performance begins when the scheduled campaign starts.': 'يبدأ الأداء اليومي مع بداية الحملة المجدولة.',
  'Taps (right axis)': 'النقرات (المحور الأيمن)', 'Daily impressions and taps': 'مرات الظهور والنقرات اليومية',
  'Bar chart from': 'رسم بالأعمدة من', 'through': 'حتى', 'impressions,': 'مرة ظهور،', 'taps': 'نقرة',
  'No icon matches “': 'لا توجد أيقونة تطابق «', 'total)': 'إجمالاً)',
  'Any child categories are reassigned to this category&apos;s parent. If places are still assigned to it, those places are set to': 'تنقل التصنيفات الفرعية إلى التصنيف الرئيسي. إذا بقيت أماكن مرتبطة به، تحول حالتها إلى',
  'draft': 'مسودة', '(hidden from the site) and the category is removed from the dashboard rather than erased from the database — places must keep pointing at a category that exists.': '(مخفية عن الموقع) ويزال التصنيف من لوحة التحكم دون محوه من قاعدة البيانات؛ يجب أن تبقى الأماكن مرتبطة بتصنيف موجود.',
  'Delete this category?': 'حذف هذا التصنيف؟', 'This will remove the category and break any place currently filed under it. This cannot be undone.': 'سيزيل هذا التصنيف ويؤثر على الأماكن المرتبطة به. لا يمكن التراجع عن ذلك.',
  'Back to categories': 'العودة للتصنيفات', 'Name (English)': 'الاسم بالإنجليزية',
  'Cover photo': 'صورة الغلاف', 'Cover photo *': 'صورة الغلاف *', 'Add photo': 'إضافة صورة', 'Remove': 'إزالة',
  'Governorate *': 'المحافظة *', 'Regions / areas in this city': 'المناطق والأحياء في هذه المدينة',
  'Description (Arabic)': 'الوصف بالعربية', 'Description (English)': 'الوصف بالإنجليزية',
  'No governorate matches “': 'لا توجد محافظة تطابق «', 'area': 'منطقة', 'selected': 'محدد', 'No areas match “': 'لا توجد مناطق تطابق «',
  'Pick the city (governorate) first — its areas appear here to choose from.': 'اختر المدينة (المحافظة) أولاً لتظهر مناطقها هنا.',
  'Deleted': 'محذوف', 'English': 'الإنجليزية', 'active)': 'نشط)', 'Add your first city': 'إضافة أول مدينة',
  'This city will be hidden from the public list. Areas/districts under this city will remain (no cascade).': 'ستخفى المدينة من القائمة العامة. تبقى مناطقها وأحياؤها دون حذف.',
  'Restore': 'استعادة', 'The city will be restored to its prior status and reappear on the public list.': 'تستعاد المدينة لحالتها السابقة وتظهر مجدداً في القائمة العامة.',
  'Back to cities': 'العودة للمدن', 'Recommended 1200×800 (3:2), min 800×600. 16:9 also works. Auto-optimized to WebP.': 'يفضل ١٢٠٠×٨٠٠ (٣:٢)، والحد الأدنى ٨٠٠×٦٠٠. تقبل ١٦:٩ أيضاً. تحسن تلقائياً إلى WebP.',
  'Couldn&apos;t load insights.': 'تعذر تحميل الإحصاءات.',
  'The analytics endpoint didn&apos;t respond. This is the only thing on this page that failed — the rest of the dashboard is unaffected.': 'لم تستجب خدمة الإحصاءات. هذا الجزء فقط تعذر تحميله؛ بقية لوحة التحكم لم تتأثر.',
  'Engagement': 'التفاعل', 'Catalogue': 'الدليل', 'Ranked by': 'الترتيب حسب', 'Most-viewed places': 'الأماكن الأكثر مشاهدة', 'No places yet.': 'لا توجد أماكن بعد.',
  'Place Details': 'بيانات المكان', 'Auto-filled from the name and kept unique on save. Edit it if you want a custom URL.': 'يملأ تلقائياً من الاسم ويظل فريداً عند الحفظ. عدله إذا أردت رابطاً مخصصاً.',
  'City *': 'المدينة *', 'Category *': 'التصنيف *', 'Area *': 'المنطقة *', 'Google Maps link *': 'رابط خرائط Google *',
  'Pick which amenities this place has. Only amenities created in the catalog appear.': 'اختر مرافق المكان. تظهر فقط المرافق التي أنشئت في الدليل.',
  'No amenities exist in the catalog yet.': 'لا توجد مرافق في الدليل بعد.', 'Create amenities →': 'إنشاء مرافق ←',
  'Tag this place (family-friendly, outdoor…). Only tags created in the catalog appear.': 'أضف وسوم المكان (مناسب للعائلة، في الهواء الطلق…). تظهر فقط وسوم الدليل.',
  'No tags exist in the catalog yet.': 'لا توجد وسوم في الدليل بعد.', 'Create tags →': 'إنشاء وسوم ←',
  'Opening hours': 'مواعيد العمل', 'Set the week now, or leave it and add hours later on the place.': 'حدد مواعيد الأسبوع الآن أو أضفها لاحقاً من صفحة المكان.',
  'Media': 'الوسائط', 'The cover is on the Details tab. Add more gallery photos here — they upload with the place.': 'الغلاف في تبويب البيانات. أضف صور المعرض هنا لرفعها مع المكان.',
  'Current:': 'الحالي:', '(not in the list — pick one below to normalise it)': '(غير موجود في القائمة؛ اختر منطقة أدناه لتوحيدها)', 'No region matches “': 'لا توجد منطقة تطابق «',
  'Quick presets — applies to every day': 'قوالب سريعة تطبق على كل الأيام', 'Paste hours from Google Maps': 'لصق المواعيد من خرائط Google',
  'On Google Maps, expand the opening hours, select the whole block and copy it. Paste it here — English or Arabic, 12- or 24-hour, &ldquo;Closed&rdquo; and &ldquo;Open 24 hours&rdquo; all work.': 'افتح مواعيد العمل في خرائط Google وانسخها بالكامل ثم الصقها هنا. يدعم العربية والإنجليزية ونظامي ١٢ و٢٤ ساعة و«مغلق» و«مفتوح ٢٤ ساعة».',
  'Filled': 'تم ملء', 'day': 'يوم', 'Check the week below before saving.': 'راجع مواعيد الأسبوع أدناه قبل الحفظ.',
  'Pick days, then set their hours': 'اختر الأيام ثم حدد مواعيدها', 'The week': 'الأسبوع', 'Closed': 'مغلق',
  'Any status': 'كل الحالات', 'Any city': 'كل المدن', 'Any category': 'كل التصنيفات', 'Any media': 'كل الوسائط',
  'Has media': 'توجد وسائط', 'Needs media': 'يحتاج وسائط', 'Failed to load places': 'تعذر تحميل الأماكن', 'Yes': 'نعم', 'No': 'لا',
  'This place will be hidden from the public list. You can restore it later from the Deleted filter.': 'سيخفى المكان من القائمة العامة. يمكنك استعادته لاحقاً من فلتر المحذوفات.',
  'The place returns as a draft — it stays hidden from the public list until you publish it again.': 'يعود المكان كمسودة؛ يظل مخفياً عن القائمة العامة حتى تنشره مجدداً.',
  'Failed to load place': 'تعذر تحميل المكان', 'Place not found': 'المكان غير موجود', 'Area (region)': 'المنطقة', 'Google Maps link': 'رابط خرائط Google',
  'Pick which amenities this place has. Changes are sent to the public detail on save.': 'اختر مرافق المكان. تظهر التغييرات في بيانات المكان العامة عند الحفظ.',
  'Place is soft-deleted. Amenities are read-only.': 'المكان محذوف مؤقتاً. المرافق للعرض فقط.', 'Failed to load amenities catalog.': 'تعذر تحميل دليل المرافق.',
  'Create amenities in catalog →': 'إنشاء مرافق في الدليل ←', 'No amenities assigned yet — pick from the catalog.': 'لا توجد مرافق مرتبطة بعد؛ اختر من الدليل.',
  'Tag this place (family-friendly, outdoor…) so visitors can filter by vibe. Changes are sent to the public detail on save.': 'أضف وسوم المكان (مناسب للعائلة، في الهواء الطلق…) لتسهيل البحث للزوار. تظهر التغييرات للعامة عند الحفظ.',
  'Place is soft-deleted. Tags are read-only.': 'المكان محذوف مؤقتاً. الوسوم للعرض فقط.', 'Failed to load tags catalog.': 'تعذر تحميل دليل الوسوم.',
  'Create tags in catalog →': 'إنشاء وسوم في الدليل ←', 'No tags assigned yet — pick from the catalog.': 'لا توجد وسوم مرتبطة بعد؛ اختر من الدليل.',
  'Set when this place is open each day. Mark a day closed to hide its hours on the public detail. Saved with the place.': 'حدد مواعيد العمل اليومية. حدد اليوم كمغلق لإخفاء مواعيده عن العامة. تحفظ مع بيانات المكان.',
  'Place is soft-deleted. Hours are read-only.': 'المكان محذوف مؤقتاً. المواعيد للعرض فقط.', 'Photos &amp; videos': 'الصور والفيديوهات',
  'Place is soft-deleted. Photos are read-only.': 'المكان محذوف مؤقتاً. الصور للعرض فقط.', 'No photos yet — add the first one above.': 'لا توجد صور بعد؛ أضف أول صورة أعلاه.',
  'Cover': 'الغلاف', 'Set cover': 'تعيين كغلاف', 'Videos': 'الفيديوهات', 'Upload short clips (MP4/WebM, up to 100MB each). They stream in the place&apos;s public gallery.': 'ارفع مقاطع قصيرة (MP4/WebM، حتى ١٠٠ ميجابايت لكل مقطع). تعرض في معرض المكان العام.', 'No videos yet.': 'لا توجد فيديوهات بعد.',
  'Insights': 'الإحصاءات', 'What visitors are doing across the catalogue.': 'نشاط الزوار في دليل الأماكن.',
  'Settings': 'الإعدادات', 'Manage your own account.': 'إدارة حسابك.', 'Account': 'الحساب',
  'Settings specific to your admin account.': 'إعدادات حسابك الإداري.', 'Danger zone': 'إجراءات حساسة',
  'Irreversible actions affecting the entire site. Super admin only.': 'إجراءات لا يمكن التراجع عنها تؤثر على الموقع بالكامل. للمسؤول الأعلى فقط.',
  'Admins': 'المسؤولون', 'Add admin': 'إضافة مسؤول', 'Edit admin': 'تعديل المسؤول', 'Admin details': 'بيانات المسؤول',
  'Email': 'البريد الإلكتروني', 'Password': 'كلمة المرور', 'Initial password': 'كلمة المرور الأولية',
  'Role': 'الدور', 'Super admin': 'مسؤول أعلى', 'Admin': 'مسؤول', 'Viewer': 'مشاهد', 'Editor': 'محرر',
  'Active': 'نشط', 'Disabled': 'معطل', 'Draft': 'مسودة', 'Status': 'الحالة', 'Last login': 'آخر دخول',
  'Created': 'تاريخ الإنشاء', 'Actions': 'الإجراءات', 'Action': 'الإجراء', 'Edit': 'تعديل', 'Delete': 'حذف',
  'Disable': 'تعطيل', 'Enable': 'تفعيل', '(you)': '(أنت)', 'Cancel': 'إلغاء', 'Retry': 'إعادة المحاولة',
  'Refresh': 'تحديث', 'Previous': 'السابق', 'Prev': 'السابق', 'Next': 'التالي', 'Page': 'الصفحة', 'of': 'من',
  'Back to admins': 'العودة للمسؤولين', 'Admin not found': 'المسؤول غير موجود', 'No admins yet': 'لا يوجد مسؤولون بعد',
  'Failed to load admin': 'تعذر تحميل المسؤول', 'Failed to load admins': 'تعذر تحميل المسؤولين',
  'Admin management is restricted to super admins.': 'إدارة المسؤولين متاحة للمسؤول الأعلى فقط.',
  'You don&apos;t have access to this page': 'ليس لديك صلاحية لهذه الصفحة', 'Add the first admin': 'إضافة أول مسؤول',
  'Delete admin': 'حذف المسؤول', 'Disable admin': 'تعطيل المسؤول', 'Re-enable': 'إعادة التفعيل',
  'Manage who can sign in to the dashboard and what they can do.': 'إدارة من يمكنه دخول لوحة التحكم وصلاحياته.',
  'Must be at least 8 characters. The admin should change this on first login.': 'ثمانية أحرف على الأقل. على المسؤول تغييرها عند أول دخول.',
  'Email is set at creation and cannot be changed here.': 'يحدد البريد عند الإنشاء ولا يمكن تغييره هنا.',
  'You cannot change your own role.': 'لا يمكنك تغيير دورك.', 'Created:': 'تاريخ الإنشاء:', 'Last login:': 'آخر دخول:',
  'Dashboard': 'لوحة التحكم', 'New': 'جديد', 'Name': 'الاسم', 'Name *': 'الاسم *', 'English Name': 'الاسم بالإنجليزية',
  'Arabic Name': 'الاسم بالعربية', 'Name (Arabic) *': 'الاسم بالعربية *', 'Name (English) *': 'الاسم بالإنجليزية *',
  'Slug': 'المعرف النصي', 'Slug *': 'المعرف النصي *', 'Icon': 'الأيقونة', 'Sort order': 'ترتيب العرض',
  'Categories': 'التصنيفات', 'Add Category': 'إضافة تصنيف', 'New Category': 'تصنيف جديد', 'Edit Category': 'تعديل التصنيف',
  'Category Details': 'بيانات التصنيف', 'Parent category': 'التصنيف الرئيسي', '(none — top-level)': '(بدون — المستوى الرئيسي)',
  'Failed to load categories': 'تعذر تحميل التصنيفات', 'Failed to load category': 'تعذر تحميل التصنيف',
  'Category not found': 'التصنيف غير موجود', 'Add your first category': 'إضافة أول تصنيف',
  'Cities': 'المدن', 'Add City': 'إضافة مدينة', 'New City': 'مدينة جديدة', 'Edit City': 'تعديل المدينة',
  'City Details': 'بيانات المدينة', 'Failed to load cities': 'تعذر تحميل المدن', 'Failed to load city': 'تعذر تحميل المدينة',
  'City not found': 'المدينة غير موجودة', 'Region': 'المنطقة', 'Parent city': 'المدينة الرئيسية',
  'Amenities': 'المرافق', 'Add Amenity': 'إضافة مرفق', 'New Amenity': 'مرفق جديد', 'Edit Amenity': 'تعديل المرفق',
  'Amenity Details': 'بيانات المرفق', 'Failed to load amenities': 'تعذر تحميل المرافق',
  'Failed to load amenity': 'تعذر تحميل المرفق', 'Amenity not found': 'المرفق غير موجود', 'No amenities found': 'لم يتم العثور على مرافق',
  'Tags': 'الوسوم', 'Add Tag': 'إضافة وسم', 'New Tag': 'وسم جديد', 'Edit Tag': 'تعديل الوسم', 'Tag Details': 'بيانات الوسم',
  'Failed to load tags': 'تعذر تحميل الوسوم', 'Failed to load tag': 'تعذر تحميل الوسم', 'Tag not found': 'الوسم غير موجود', 'No tags found': 'لم يتم العثور على وسوم',
  'Places': 'الأماكن', 'Place': 'المكان', 'Add Place': 'إضافة مكان', 'New Place': 'مكان جديد', 'Edit Place': 'تعديل المكان',
  'City': 'المدينة', 'Category': 'التصنيف', 'Description': 'الوصف', 'Address': 'العنوان', 'Phone': 'الهاتف',
  'Latitude': 'خط العرض', 'Longitude': 'خط الطول', 'Website': 'الموقع الإلكتروني', 'Featured': 'مميز',
  'Clear': 'مسح', 'Selected:': 'المحدد:', 'All cities (27 governorates)': 'كل المدن (٢٧ محافظة)',
  'Opening time': 'وقت الفتح', 'Closing time': 'وقت الإغلاق', 'to': 'إلى', 'All': 'الكل', 'None': 'بدون',
  'Fill hours from this': 'ملء المواعيد من النص', 'Mark closed': 'تحديد كمغلق', 'Sun–Thu': 'الأحد–الخميس', 'Fri–Sat': 'الجمعة–السبت',
  'Sunday': 'الأحد', 'Monday': 'الاثنين', 'Tuesday': 'الثلاثاء', 'Wednesday': 'الأربعاء', 'Thursday': 'الخميس', 'Friday': 'الجمعة', 'Saturday': 'السبت',
  'Campaigns': 'الحملات', 'Inventory': 'السعة الإعلانية', 'Top 10 preview': 'معاينة أفضل ١٠', 'New campaign': 'حملة جديدة',
  'Placement': 'موضع الإعلان', 'Featured · national': 'مميز · على مستوى مصر', 'Top 10': 'أفضل ١٠', 'All Egypt': 'كل مصر',
  'Advertiser': 'المعلن', 'Advertiser and payment record': 'بيانات المعلن والدفع', 'Dates': 'التواريخ', 'Amount': 'المبلغ',
  'Impressions': 'مرات الظهور', 'Taps': 'النقرات', 'CTR': 'معدل النقر', 'State': 'الحالة', 'Clear filter': 'مسح الفلتر',
  'Open report': 'فتح التقرير', 'Open campaign': 'فتح الحملة', 'Campaign created.': 'تم إنشاء الحملة.',
  'Inventory warning': 'تنبيه السعة', 'No campaigns in this view': 'لا توجد حملات في هذا العرض',
  'Try another state or create a campaign to book inventory.': 'جرّب حالة أخرى أو أنشئ حملة لحجز السعة.',
  'The booking is saved. Oversold campaigns rotate fairly.': 'تم حفظ الحجز. تتناوب الحملات التي تجاوزت السعة بشكل عادل.',
  'Campaign targeting can only change while scheduled.': 'يمكن تغيير استهداف الحملة فقط أثناء جدولتها.',
  'Place, placement and city are locked because this campaign is no longer scheduled.': 'المكان والموضع والمدينة مقفلة لأن الحملة لم تعد مجدولة.',
  'City scope': 'نطاق المدينة', 'Eligible candidates': 'الأماكن المؤهلة', 'Ranked list': 'قائمة الترتيب',
  'Sponsored slot': 'موضع ممول', 'Score': 'النتيجة', 'Sponsored queue': 'قائمة الحملات الممولة', '4 weeks': '٤ أسابيع', 'Today': 'اليوم',
  'No inventory scopes available': 'لا توجد نطاقات سعة متاحة', 'Active city scopes will appear here when the API returns them.': 'تظهر نطاقات المدن النشطة هنا عند إتاحتها من الخدمة.',
  'Each cell shows booked / capacity. Select a booked day to view those campaigns.': 'تعرض كل خلية المحجوز / السعة. اختر يوماً محجوزاً لعرض حملاته.',
  'Scope': 'النطاق', 'Campaign': 'الحملة', 'Print / Save PDF': 'طباعة / حفظ PDF', 'Daily performance': 'الأداء اليومي',
  'Daily detail': 'التفاصيل اليومية', 'Date': 'التاريخ', 'Reach': 'الوصول', 'No daily rows yet.': 'لا توجد بيانات يومية بعد.',
  'How these numbers are measured': 'كيف تقاس هذه الأرقام', 'Views': 'المشاهدات', 'Saves': 'الحفظ', 'Directions': 'طلبات الاتجاهات',
  'Try again': 'حاول مرة أخرى', 'Where the engagement is': 'أين يحدث التفاعل', 'By city': 'حسب المدينة', 'By area': 'حسب المنطقة',
  'Storefront': 'واجهة الموقع', 'Homepage sections': 'أقسام الصفحة الرئيسية', 'Add a section': 'إضافة قسم',
  'Key *': 'المفتاح *', 'Kind *': 'النوع *', 'Top rated': 'الأعلى تقييماً', 'Recommended': 'موصى به', 'Custom (pinned)': 'مخصص (مثبت)',
  'Title (Arabic) *': 'العنوان بالعربية *', 'Title (English)': 'العنوان بالإنجليزية',
  'Control which sections appear on the public homepage and in what order.': 'تحديد الأقسام التي تظهر في الصفحة الرئيسية وترتيبها.',
  'No sections yet. Add one below — it will show on the homepage.': 'لا توجد أقسام بعد. أضف قسماً أدناه ليظهر في الصفحة الرئيسية.',
  'Footer &amp; social': 'التذييل والتواصل الاجتماعي', 'Shown in the website footer and the app. Leave a field blank to hide that icon.': 'تظهر في تذييل الموقع والتطبيق. اترك الحقل فارغاً لإخفاء أيقونته.',
  'API keys': 'مفاتيح API', 'Name / prefix': 'الاسم / البادئة', 'Permissions': 'الصلاحيات', 'Last used': 'آخر استخدام', 'Expires': 'انتهاء الصلاحية',
  'Revoke': 'إلغاء المفتاح', 'Revoke API key?': 'إلغاء مفتاح API؟', 'No keys on this page': 'لا توجد مفاتيح في هذه الصفحة',
  'Create a named key for each AI assistant so you can revoke access independently.': 'أنشئ مفتاحاً باسم لكل مساعد لتتمكن من إلغاء صلاحياته منفرداً.',
  'Your API key': 'مفتاح API الخاص بك', 'AI client': 'عميل الذكاء الاصطناعي', 'Copy config': 'نسخ الإعدادات',
  'Save this key now. It will not be shown again. Closing this dialog removes it from this page.': 'احفظ المفتاح الآن؛ لن يظهر مرة أخرى. إغلاق النافذة يزيله من الصفحة.',
  'I have saved it · Close': 'حفظته · إغلاق', 'Expiry (optional, your local time)': 'انتهاء الصلاحية (اختياري، بتوقيتك المحلي)',
  'Change password': 'تغيير كلمة المرور', 'Update your password': 'تحديث كلمة المرور', 'Current password': 'كلمة المرور الحالية',
  'New password': 'كلمة المرور الجديدة', 'Confirm new password': 'تأكيد كلمة المرور الجديدة',
  'At least 8 characters with 1 letter and 1 number.': 'ثمانية أحرف على الأقل، منها حرف ورقم.',
  'You will stay signed in on this device after the change.': 'ستبقى مسجلاً للدخول على هذا الجهاز بعد التغيير.',
  'Sign in': 'تسجيل الدخول', 'Signing in…': 'جارٍ تسجيل الدخول…', 'Khargny admin dashboard': 'لوحة إدارة خرجني',
  'Connection error. Try again.': 'تعذر الاتصال. حاول مرة أخرى.', 'Invalid email or password': 'البريد الإلكتروني أو كلمة المرور غير صحيحين',
  'Too many attempts. Try again in a few minutes.': 'محاولات كثيرة. حاول مجدداً بعد بضع دقائق.',
};

export function translateDashboardCopy(value: string, lang: 'ar' | 'en') {
  if (lang === 'en') return value;
  const key = value.replace(/\s+/g, ' ').trim();
  const match = Object.entries(dashboardCopy).find(([candidate]) => candidate.replaceAll('&apos;', "'").replaceAll('&amp;', '&').replaceAll('&quot;', '"').replaceAll('&ldquo;', '“').replaceAll('&rdquo;', '”') === key);
  return match?.[1] ?? value;
}
