import { analyticsCopy } from '@/lib/analytics-copy';

const round6bCopy: Record<string, string> = {
  'Expired': 'منتهي',
  'Could not load cities. Try again.': 'تعذر تحميل المدن. حاول مرة أخرى.',
  'Saved, but the page could not refresh': 'تم الحفظ، لكن تعذر تحديث الصفحة',
  'Close': 'إغلاق',
  'Current subscription': 'الاشتراك الحالي',
  'EGP': 'جنيه',
  'Enter a non-negative amount with at most two decimal places.': 'أدخل مبلغًا غير سالب بمنزلتين عشريتين كحد أقصى.',
  'This plan is unavailable. Choose an active plan.': 'هذه الخطة غير متاحة. اختر خطة مفعّلة.',
  'Use nonblank names up to 200 characters and descriptions up to 1000 characters.': 'استخدم أسماء غير فارغة بحد أقصى ٢٠٠ حرف، وأوصافًا بحد أقصى ١٠٠٠ حرف.',
  'A place gets it when its non-hidden price list has at least one visible item or service.': 'يحصل المكان عليها عندما تحتوي قائمة أسعاره غير المخفية على عنصر أو خدمة ظاهرة واحدة على الأقل.',
  'Badge and legend preview': 'معاينة الشارة والنص التوضيحي',
  'Hidden everywhere. Places keep the badge and it returns when you switch this on.': 'مخفية في كل مكان. تحتفظ الأماكن بالشارة وتظهر مجددًا عند تفعيلها.',
  'Manual calculation': 'حساب يدوي',
  'Automatic calculation': 'حساب تلقائي',
  'Pins and exclusions are team decisions, not earned activity.': 'التثبيت والاستبعاد قرارات الفريق، وليسا نشاطًا مكتسبًا.',
  'Below the winning ranks': 'خارج المراتب الفائزة',
  'Could not load badge preview. Change a rule field to retry.': 'تعذر تحميل معاينة الشارة. غيّر حقلًا في القاعدة لإعادة المحاولة.',
  'Enter a valid display order (0–10000).': 'أدخل ترتيب عرض صالحًا (من ٠ إلى ١٠٠٠٠).',
  'Plans': 'الخطط',
  'Plan': 'الخطة',
  'Owner Plus': 'مالك بلس',
  'Plan prices': 'أسعار الخطة',
  'No price set': 'لم يُحدد سعر',
  'Catalogue price proposed; you can edit it.': 'اقتُرح سعر الكتالوج؛ يمكنك تعديله.',
  'Set prices for each length. Empty clears the price, not to zero.': 'حدد سعر كل مدة. ترك الحقل فارغًا يزيل السعر ولا يجعله صفرًا.',
  'Save plan': 'حفظ الخطة',
  'Inactive plan': 'خطة غير مفعّلة',
  'Promotion for Owner Plus is not switched on yet': 'الترويج لخطة مالك بلس غير مفعّل حتى الآن',
  'Edit places in the subscriber portal': 'تعديل الأماكن في بوابة المشترك',
  'Services and prices': 'الخدمات والأسعار',
  'Eligibility for earned badges': 'الأهلية لشارات الإنجاز',
  'Place statistics': 'إحصاءات المكان',
  'Promotion in area and category lists': 'الترويج في قوائم المنطقة والتصنيف',
  'Featured rotation': 'التناوب في الأماكن المميزة',
  'City Top 10 rotation': 'التناوب في أفضل ١٠ أماكن بالمدينة',
  'Monthly report': 'التقرير الشهري',
  'Could not load plans. Try again.': 'تعذر تحميل الخطط. أعد المحاولة.',
  'Could not save this plan. Try again.': 'تعذر حفظ هذه الخطة. أعد المحاولة.',
  'Change plan': 'تغيير الخطة',
  'Confirm plan change': 'تأكيد تغيير الخطة',
  'This closes the current period now and links a new period ending on the same date. Recorded payments stay on the old period.': 'ينهي هذا الإجراء الفترة الحالية الآن ويربطها بفترة جديدة تنتهي في التاريخ نفسه. تظل المدفوعات المسجلة في الفترة القديمة.',
  'The server returns the exact difference after confirmation. No payment or refund is recorded by this action.': 'يرجع الخادم الفرق الدقيق بعد التأكيد. لا يسجل هذا الإجراء دفعة أو رد مبلغ.',
  'Plan changed': 'تم تغيير الخطة',
  'Server-computed difference': 'الفرق المحسوب بواسطة الخادم',
  'for the remaining': 'عن المدة المتبقية:',
  'Credit; no automatic refund.': 'رصيد مستحق؛ لا يوجد رد مبلغ تلقائي.',
  'No payment recorded.': 'لم تُسجل دفعة.',
  'Changed from period': 'تغيّرت من الفترة',
  'Replaced by period': 'استُبدلت بالفترة',
  'Superseded': 'مستبدل',
  'Both plans need a one-month price before a paid change.': 'يجب تحديد سعر شهر واحد لكلتا الخطتين قبل تغيير اشتراك مدفوع.',
  'This trial has already been used for this place.': 'استُخدمت هذه التجربة لهذا المكان بالفعل.',
  'Only a super admin may repeat a trial.': 'يمكن للمسؤول الأعلى فقط تكرار التجربة.',
  'Trials cannot include a payment.': 'لا يمكن تسجيل دفعة للتجارب المجانية.',
  'Badges': 'الشارات',
  'Badge sections': 'أقسام الشارات',
  'Status badges': 'شارات الحالة',
  'Achievement badges': 'شارات الإنجاز',
  'Overrides': 'الاستثناءات',
  'The marks a place can carry on the website and the app. Status badges are given by the team; achievement badges are earned from visitor activity.': 'العلامات التي يحملها المكان على الموقع والتطبيق. يمنح الفريق شارات الحالة، وتُكتسب شارات الإنجاز من نشاط الزوار.',
  'Badges are not available on this server yet': 'الشارات غير متاحة على هذا الخادم بعد',
  'Could not load badges. Try again.': 'تعذر تحميل الشارات. أعد المحاولة.',
  'Could not save this badge. Try again.': 'تعذر حفظ هذه الشارة. أعد المحاولة.',
  'Hidden everywhere': 'مخفية في كل مكان',
  'Show on the website and app': 'إظهار على الموقع والتطبيق',
  'Changes are live at once': 'التغييرات تُنشر فورًا',
  'How a place gets it': 'كيف يحصل المكان عليها',
  'A place gets it when it has at least one visible priced item or service.': 'يحصل عليها المكان عندما يتوفر له عنصر أو خدمة ظاهرة بسعر.',
  'A place gets it when the team has reviewed its prices.': 'يحصل عليها المكان عندما يراجع الفريق أسعاره.',
  'A place gets it when a team visit is recorded.': 'يحصل عليها المكان عند تسجيل زيارة من الفريق.',
  'Places holding it': 'الأماكن الحاصلة عليها',
  'Edit wording': 'تعديل النص',
  'Arabic name': 'الاسم بالعربية',
  'English name': 'الاسم بالإنجليزية',
  'Arabic description': 'الوصف بالعربية',
  'English description': 'الوصف بالإنجليزية',
  'Badge icon': 'أيقونة الشارة',
  'Display order': 'ترتيب العرض',
  'Tag icon': 'أيقونة بطاقة',
  'Price check icon': 'أيقونة مراجعة السعر',
  'Visit mark icon': 'أيقونة الزيارة',
  'Flame icon': 'أيقونة شعلة',
  'Heart icon': 'أيقونة قلب',
  'Eye icon': 'أيقونة عين',
  'Save wording': 'حفظ النص',
  'Enter names and descriptions in both languages.': 'أدخل الاسم والوصف باللغتين.',
  'Rule': 'القاعدة',
  'Give it to the top': 'امنحها لأفضل',
  'places in each': 'أماكن في كل',
  'City and category': 'مدينة وتصنيف',
  'by': 'حسب',
  'saves': 'مرات الحفظ',
  'views': 'المشاهدات',
  'over': 'خلال',
  '90 days': '٩٠ يومًا',
  'All time': 'كل الوقت',
  'if they have at least': 'إذا حققت على الأقل',
  'Winners per scope': 'الفائزون في كل نطاق',
  'Minimum activity': 'الحد الأدنى للنشاط',
  'Activity window': 'فترة النشاط',
  'Award scope': 'نطاق المنح',
  'Activity from paid placements is not counted.': 'لا يُحتسب نشاط الظهور المدفوع.',
  'Use 1–10 winners and a whole-number minimum of at least 1.': 'اختر من ١ إلى ١٠ فائزين وحدًا أدنى صحيحًا لا يقل عن ١.',
  'With this rule': 'بهذه القاعدة',
  'places would hold it': 'أماكن ستحصل عليها',
  'now': 'حاليًا',
  'Save rules': 'حفظ القواعد',
  'rule changed': 'تغيّرت القاعدة',
  'Saved. The holders are being recalculated': 'تم الحفظ. يجري إعادة حساب الحاصلين على الشارات',
  'Recalculation is still pending. Refresh to check again.': 'إعادة الحساب لم تكتمل بعد. حدّث للتحقق مجددًا.',
  'Holders now': 'الحاصلون عليها الآن',
  'No place has reached this yet.': 'لم يصل أي مكان إلى هذا المستوى بعد.',
  'No places hold this status badge yet.': 'لا توجد أماكن تحمل شارة الحالة بعد.',
  'Floor': 'الحد الأدنى',
  'Closest': 'الأقرب',
  'needs': 'يحتاج إلى',
  'Below the winners': 'بعد الفائزين',
  'Just below the line': 'أسفل حد الفوز مباشرة',
  'Rank': 'الترتيب',
  'Value': 'القيمة',
  'Pinned': 'مثبّتة',
  'Earned': 'مكتسبة',
  'Excluded': 'مستثنى',
  'Held': 'حاصل عليها',
  'Not held': 'غير حاصل عليها',
  'in': 'في',
  'Not eligible: publish the place and add a photo or video.': 'غير مؤهل: انشر المكان وأضف صورة أو فيديو.',
  'Excluded by the team': 'استثناه الفريق',
  'Pinned by the team': 'ثبّتها الفريق',
  'Open place': 'فتح المكان',
  'Exclude from this badge': 'استثناء من هذه الشارة',
  'Remove pin': 'إزالة التثبيت',
  'Last run': 'آخر تشغيل',
  'No run recorded yet': 'لم يُسجل تشغيل بعد',
  'Candidates': 'المرشحون',
  'Awards': 'الشارات الممنوحة',
  'Run completed': 'اكتمل التشغيل',
  'Run failed; previous awards are kept.': 'فشل التشغيل؛ بقيت الشارات السابقة.',
  'Run in progress': 'التشغيل جارٍ',
  'Run now': 'تشغيل الآن',
  'Recalculate achievement badges now?': 'إعادة حساب شارات الإنجاز الآن؟',
  'This replaces earned awards using current rules and overrides. Existing awards remain if calculation fails.': 'يستبدل الشارات المكتسبة وفق القواعد والاستثناءات الحالية. تظل الشارات السابقة إذا فشل الحساب.',
  'Another run is already in progress.': 'هناك تشغيل آخر جارٍ بالفعل.',
  'Calculated through yesterday in Cairo. The next read may start a refresh; this is not a timed schedule.': 'يُحتسب النشاط حتى أمس بتوقيت القاهرة. قد تبدأ القراءة التالية تحديثًا؛ هذا ليس جدول تشغيل محددًا.',
  'Next check day': 'يوم التحقق التالي',
  'Refresh due on read': 'التحديث مطلوب عند القراءة',
  'Add override': 'إضافة استثناء',
  'Override state': 'حالة الاستثناء',
  'No overrides. Pins and exclusions are team decisions, not earned activity.': 'لا توجد استثناءات. التثبيت والاستثناء قرارات الفريق وليسا نشاطًا مكتسبًا.',
  'Badge': 'الشارة',
  'Until': 'حتى',
  'No end': 'بلا نهاية',
  'Reason': 'السبب',
  'Added by': 'أضافه',
  'Remove override?': 'إزالة الاستثناء؟',
  'This removes the team decision. The badge will follow its rule again after recalculation.': 'يزيل قرار الفريق. ستتبع الشارة قاعدتها مجددًا بعد إعادة الحساب.',
  'Exclude: this place does not get this badge': 'استثناء: لا يحصل هذا المكان على الشارة',
  'Pin: this place shows this badge until a date, whatever its numbers': 'تثبيت: يعرض المكان الشارة حتى تاريخ محدد مهما كانت أرقامه',
  'End date (Cairo)': 'تاريخ النهاية (القاهرة)',
  'A pin needs an end date within 90 days. It expires at the end of that Cairo day.': 'يحتاج التثبيت إلى تاريخ نهاية خلال ٩٠ يومًا. ينتهي بنهاية ذلك اليوم بتوقيت القاهرة.',
  'Shown to the team in the log': 'يظهر للفريق في السجل',
  'This place already has an override for this badge. Remove it first.': 'يوجد استثناء لهذا المكان وهذه الشارة بالفعل. أزله أولًا.',
  'Choose a place, a reason and a valid future end date.': 'اختر مكانًا وسببًا وتاريخ نهاية صالحًا في المستقبل.',
  'Reason is required (at most 1000 characters).': 'السبب مطلوب (١٠٠٠ حرف كحد أقصى).',
  'Could not load holders. Try again.': 'تعذر تحميل الحاصلين على الشارة. أعد المحاولة.',
  'Could not load overrides. Try again.': 'تعذر تحميل الاستثناءات. أعد المحاولة.',
  'Could not save the override. Try again.': 'تعذر حفظ الاستثناء. أعد المحاولة.',
  'Search places': 'ابحث عن مكان',
  'Choose this place': 'اختيار هذا المكان',
  'No matching places. Try another search.': 'لا توجد أماكن مطابقة. جرّب بحثًا آخر.',
  'Badge explanations are unavailable on this server.': 'تفسير الشارات غير متاح على هذا الخادم.',
};

const round6CombinedCopy: Record<string, string> = {
  'Inactive': 'غير نشط',
  'Expiring within 30 days': 'ينتهي خلال ٣٠ يوماً',
  'All holders': 'كل الحاصلين على الشارة',
  'All badges': 'كل الشارات',
  'All override states': 'كل حالات الاستثناء',
  'All override kinds': 'كل أنواع الاستثناءات',
  'All badge families': 'كل أنواع الشارات',
  'All badge states': 'كل حالات الشارات',
  'All plan states': 'كل حالات الخطط',
  'All link states': 'كل حالات الربط',
  'Already linked': 'مرتبط بالفعل',
  'Newly chosen': 'مختار حديثًا',
  'All expiry dates': 'كل مواعيد الانتهاء',
  'All places': 'كل الأماكن',
  'All consent states': 'كل حالات الموافقة',
  'Consent recorded': 'الموافقة مسجلة',
  'No photo consent recorded': 'لم تُسجل موافقة التصوير',
  'All media types': 'كل أنواع الوسائط',
  'All payment methods': 'كل طرق الدفع',
};

export const dashboardCopy: Record<string, string> = {
  ...round6CombinedCopy,
  // Round 6A: separate bilingual Analytics and list-rule additions.
  ...analyticsCopy,
  // Round 6B: Badges and Plans additions.
  ...round6bCopy,
  "Since": "منذ",
  "shown": "مرة ظهور",
  "Not promoted by a campaign.": "لا يُروّج له عبر حملة إعلانية.",
  "Not shown: no photos": "لا يظهر: لا توجد صور",
  "Country code": "رمز الدولة",
  "Name is required.": "الاسم مطلوب.",
  "Phone is required.": "الهاتف مطلوب.",
  "Only Egyptian mobile numbers can be saved right now.": "يمكن حفظ أرقام المحمول المصرية فقط حاليًا.",
  "Enter a valid email address.": "أدخل بريدًا إلكترونيًا صحيحًا.",
  "Enter a valid Egyptian mobile number (01XXXXXXXXX or +20).": "أدخل رقم محمول مصري صحيحًا (01XXXXXXXXX أو +20).",
  "Same as phone": "نفس رقم الهاتف",
  "Active, not shown: no photos": "نشط، لا يظهر: لا توجد صور",
  "Active, but not shown: add a photo": "نشط، لكنه لا يظهر: أضف صورة",
  "Live on the website": "ظاهر على الموقع",
  "Not shown: draft": "لا يظهر: مسودة",
  "Not shown: deactivated": "لا يظهر: مُعطّل",
  "Deactivated": "مُعطّل",
  "Active but not shown": "نشط لكنه لا يظهر",
  "Any active place": "أي مكان نشط",
  "Place status": "حالة المكان",
  "Deactivate this place?": "تعطيل هذا المكان؟",
  "The place will be hidden from visitors. Its media, owner and subscriptions are kept.": "سيُخفى المكان عن الزوار. تبقى وسائطه ومالكه واشتراكاته محفوظة.",
  "Save changes to apply this status.": "احفظ التغييرات لتطبيق هذه الحالة.",
  "Publish": "نشر",
  "Ads for this place": "إعلانات هذا المكان",
  "Promote this place": "روّج لهذا المكان",
  "Current campaigns": "الحملات الحالية",
  "Past campaigns": "الحملات السابقة",
  "Not promoted anywhere.": "لا يُروّج له في أي مكان.",
  "Shown in the last 30 days": "مرات الظهور في آخر ٣٠ يومًا",
  "Taps in the last 30 days": "الضغطات في آخر ٣٠ يومًا",
  "Shown and taps cover the last 30 days.": "مرات الظهور والضغطات تشمل آخر ٣٠ يومًا.",
  "Could not load this place’s campaigns. Try again.": "تعذر تحميل حملات هذا المكان. أعد المحاولة.",
  "Other promotions": "عروض ترويجية أخرى",
  "From a plan": "من خطة اشتراك",
  "By hand": "يدويًا",
  "Optional": "اختياري",
  "Could not load this section’s places.": "تعذر تحميل أماكن هذا القسم.",
  "Section places saved.": "تم حفظ أماكن القسم.",
  "Could not save the section places.": "تعذر حفظ أماكن القسم.",
  "Add item or service": "إضافة صنف أو خدمة",
  "Add group": "إضافة مجموعة",
  "Promote {place} on {surface} in {scope}, {from} to {to}, for {money}.": "روّج للمكان {place} في {surface} بنطاق {scope}، من {from} إلى {to}، مقابل {money}.",
  "Back to subscribers": "العودة للمشتركين",
  "Back to place": "العودة للمكان",
  "This removes the pin from this section only. Paid campaigns and the place are unchanged. Empty automatic sections return to automatic selection.": "يُزال التثبيت من هذا القسم فقط دون تغيير الحملات المدفوعة أو المكان. يعود القسم التلقائي الفارغ للاختيار التلقائي.",
  "places of capacity · now": "أماكن متاحة للسعة · الآن",
  "Could not load campaign details.": "تعذر تحميل تفاصيل الحملة.",
  "Campaign saved.": "تم حفظ الحملة.",
  "Campaign not found.": "الحملة غير موجودة.",
  "Choose a place": "اختر مكانًا",
  "Subscriber": "المشترك",
  "Live": "تعرض الآن",
  "Scheduled": "مجدولة",
  "Paused": "متوقفة مؤقتًا",
  "Ended + expired": "منتهية أو انتهت مدتها",
  "Report": "التقرير",
  "Key and Arabic title are required": "المعرف والعنوان بالعربية مطلوبان",
  "Sponsored": "برعاية",
  "Manage": "إدارة",
  "Title (Arabic)": "العنوان بالعربية",
  "Kind": "النوع",
  "Rating": "التقييم",
  "New subscriber": "مشترك جديد",
  "Subscriber sections": "تبويبات المشتركين",
  "The campaign will stop serving immediately. Its booked dates and history will stay intact.": "سيتوقف عرض الحملة فورًا مع الاحتفاظ بمواعيدها المحجوزة وسجلها.",
  "The campaign will be eligible to serve again whenever its booked dates are live.": "ستصبح الحملة مؤهلة للعرض مجددًا خلال مواعيدها المحجوزة.",
  "This permanently ends serving for the campaign. The record and advertiser report will remain available.": "ينتهي عرض الحملة نهائيًا مع الاحتفاظ بالسجل وتقرير المعلن.",
  "Campaign paused.": "تم إيقاف الحملة مؤقتًا.",
  "Campaign resumed.": "تم استئناف الحملة.",
  "Campaign ended.": "انتهت الحملة.",
  "Could not pause the campaign.": "تعذر إيقاف الحملة مؤقتًا.",
  "Could not resume the campaign.": "تعذر استئناف الحملة.",
  "Could not end the campaign.": "تعذر إنهاء الحملة.",
  "Choose a subscriber": "اختر مشتركاً",
  "Try another state or create a campaign to book space.": "جرّب حالة أخرى أو أنشئ حملة لحجز مساحة.",
  "No campaigns end within 7 days.": "لا توجد حملات تنتهي خلال ٧ أيام.",
  "Live paid campaigns only; editorial pins are listed in Always on.": "الحملات المدفوعة المباشرة فقط؛ التثبيتات التحريرية في تبويب العرض المستمر.",
  "Add visit": "إضافة زيارة",
  "Link a place first.": "اربط مكاناً أولاً.",
  "Subscribers list": "قائمة المشتركين",
  "Brand": "علامة تجارية",
  "Brands": "العلامات التجارية",
  "Individuals": "الأفراد",
  "Subscriber type": "نوع المشترك",
  "Brand (a known business or chain)": "علامة تجارية (نشاط معروف أو سلسلة)",
  "Internal mark only; plans and prices do not change.": "علامة داخلية فقط؛ لا تتغير الخطط أو الأسعار.",
  "Brand revenue this month": "إيرادات العلامات التجارية هذا الشهر",
  "Share of revenue this month": "حصة إيرادات هذا الشهر",
  "Where ads appear": "أين تظهر الإعلانات",
  "Always on": "عرض مستمر",
  "Results": "النتائج",
  "Promotion at a glance. Dates follow Cairo time.": "نظرة سريعة على الترويج. التواريخ بتوقيت القاهرة.",
  "Promoted now": "الأماكن المروّجة الآن",
  "Shown today": "مرات الظهور اليوم",
  "Taps today": "النقرات اليوم",
  "places · now": "مكان · الآن",
  "shows · today": "مرة ظهور · اليوم",
  "taps · today": "نقرة · اليوم",
  "Needs you": "يحتاج تدخلك",
  "Ending within 7 days": "تنتهي خلال ٧ أيام",
  "Ends on": "ينتهي في",
  "No live campaigns end within 7 days.": "لا توجد حملات مباشرة تنتهي خلال ٧ أيام.",
  "Not shown in the last 2 days": "لم تظهر خلال اليومين الماضيين",
  "No confirmed gaps in the last 2 complete Cairo days.": "لا توجد فترات غياب مؤكدة خلال آخر يومين كاملين بتوقيت القاهرة.",
  "shows · last 2 days": "مرة ظهور · آخر يومين",
  "Free capacity today": "السعة المتاحة اليوم",
  "No free capacity is reported today.": "لا توجد سعة متاحة مسجلة اليوم.",
  "free places · today": "مكان متاح · اليوم",
  "Home Featured rail": "شريط المميز في الرئيسية",
  "City Top 10": "أفضل ١٠ أماكن في المدينة",
  "How promotion works on 5argny": "كيف يعمل الترويج على خرجني",
  "Choose where visitors will see the place.": "اختر أين سيرى الزوار المكان.",
  "Choose an active place and book its dates.": "اختر مكاناً نشطاً واحجز تواريخ عرضه.",
  "The place shares the available space with other booked places.": "يتشارك المكان المساحة المتاحة مع الأماكن المحجوزة الأخرى.",
  "Read its report to see shows, taps and tap rate.": "اقرأ تقريره لمعرفة مرات الظهور والنقرات ومعدل النقر.",
  "Could not load promotion data.": "تعذر تحميل بيانات الترويج.",
  "Some campaign reports could not be read. Shown and taps include readable reports only.": "تعذر قراءة بعض تقارير الحملات. مرات الظهور والضغط تشمل التقارير المتاحة فقط.",
  "Could not load free capacity.": "تعذر تحميل الأماكن المتاحة للترويج.",
  "Could not load campaign reports.": "تعذر تحميل تقارير الحملات.",
  "Shows and taps from campaign reports. City means the booked city, not the visitor’s city.": "مرات الظهور والنقرات من تقارير الحملات. المدينة هي مدينة الحجز وليست مدينة الزائر.",
  "Report period": "فترة التقرير",
  "Last 7 days": "آخر ٧ أيام",
  "Last 30 days": "آخر ٣٠ يوماً",
  "This month": "هذا الشهر",
  "Cairo · includes today": "القاهرة · يشمل اليوم",
  "Shown": "مرات الظهور",
  "Tap rate": "معدل النقر",
  "shows · selected period": "مرة ظهور · الفترة المختارة",
  "taps · selected period": "نقرة · الفترة المختارة",
  "taps per show · selected period": "نقرات لكل ظهور · الفترة المختارة",
  "Campaign results": "نتائج الحملات",
  "Group results": "تجميع النتائج",
  "By campaign": "حسب الحملة",
  "By surface": "حسب موضع العرض",
  "By booked city": "حسب مدينة الحجز",
  "No campaigns with data for this view.": "لا توجد حملات ببيانات لهذا العرض.",
  "Where it appears": "أين يظهر",
  "Where it appears:": "أين يظهر:",
  "Top 10 appears below the city heading.": "تظهر قائمة أفضل ١٠ أسفل عنوان المدينة.",
  "Featured appears near the top of the homepage.": "يظهر شريط المميز قرب أعلى الصفحة الرئيسية.",
  "Sections appear below Featured on the homepage.": "تظهر الأقسام أسفل شريط المميز في الصفحة الرئيسية.",
  "See booked space and the homepage sections you control.": "شاهد المساحة المحجوزة وأقسام الصفحة الرئيسية التي تديرها.",
  "places of capacity": "مكان سعة إجمالية",
  "booked today": "محجوز اليوم",
  "Not sponsored": "غير مموّل",
  "Live Featured campaigns; rotation decides who is shown.": "حملات المميز المباشرة؛ التناوب يحدد ما يُعرض الآن.",
  "Shown in the current Top 10 rotation.": "المعروض في التناوب الحالي لأفضل ١٠.",
  "Could not update homepage sections. Refresh before trying again.": "تعذر تحديث أقسام الرئيسية. حدّث البيانات قبل المحاولة مجدداً.",
  "Section created.": "تم إنشاء القسم.",
  "Could not create the section.": "تعذر إنشاء القسم.",
  "No sections yet. Add one to show it on the homepage.": "لا توجد أقسام بعد. أضف قسماً لعرضه في الصفحة الرئيسية.",
  "Drag to reorder; use the menu to move with the keyboard.": "اسحب لإعادة الترتيب؛ استخدم القائمة للتحريك بلوحة المفاتيح.",
  "Edit section": "تعديل القسم",
  "Disable section": "إخفاء القسم",
  "Enable section": "إظهار القسم",
  "Delete section?": "حذف القسم؟",
  "This removes the homepage section and its pins, not the places.": "يحذف هذا قسم الرئيسية وتثبيتاته، وليس الأماكن.",
  "configured pins · now": "مكان مثبّت في الإعدادات · الآن",
  "Pins are editorial, not paid campaigns. Empty automatic sections fill by their kind.": "التثبيتات تحريرية وليست حملات مدفوعة. الأقسام التلقائية بلا تثبيتات تُملأ حسب نوعها.",
  "Key (slug)": "المفتاح (المعرّف)",
  "Create section": "إنشاء القسم",
  "Editorial homepage pins stay until removed. They are not paid campaigns.": "تبقى تثبيتات الرئيسية التحريرية حتى إزالتها. ليست حملات مدفوعة.",
  "Manage homepage sections": "إدارة أقسام الرئيسية",
  "Could not load homepage pins.": "تعذر تحميل تثبيتات الرئيسية.",
  "No places are pinned in enabled homepage sections.": "لا توجد أماكن مثبّتة في أقسام الرئيسية الظاهرة.",
  "Stop": "إيقاف",
  "Stop this homepage pin?": "إيقاف هذا التثبيت في الرئيسية؟",
  "This removes the pin from this section only. Paid campaigns and the place are unchanged.": "يزيل هذا التثبيت من هذا القسم فقط. تبقى الحملات المدفوعة والمكان دون تغيير.",
  "Manage the footer and social links shown to visitors.": "إدارة تذييل الصفحة وروابط التواصل التي تظهر للزوار.",
  "Who": "مَن",
  "Where": "أين",
  "When": "متى",
  "Money": "المبلغ",
  "Campaign steps": "خطوات الحملة",
  "Needs attention": "يحتاج مراجعة",
  "Choose who to promote": "اختر مَن تروّج له",
  "A place": "مكان",
  "A subscriber’s place": "مكان مشترك",
  "Search subscriber": "ابحث عن مشترك",
  "Subscriber’s place": "مكان المشترك",
  "Choose an active place.": "اختر مكاناً نشطاً.",
  "Could not load this place.": "تعذر تحميل هذا المكان.",
  "This subscriber has no linked places.": "هذا المشترك ليس لديه أماكن مرتبطة.",
  "Update the booked promotion and advertiser details.": "تحديث الترويج المحجوز وبيانات المعلن.",
  "Choose who, where, when and money before booking.": "اختر المكان وموضع العرض والموعد والمبلغ قبل الحجز.",
  "Place, surface and city are locked because this campaign is no longer scheduled.": "المكان وموضع العرض والمدينة غير قابلة للتغيير لأن الحملة لم تعد مجدولة.",
  "Featured appears across all Egypt.": "يظهر شريط المميز في كل مصر.",
  "Campaign length": "مدة الحملة",
  "7 days": "٧ أيام",
  "14 days": "١٤ يوماً",
  "30 days": "٣٠ يوماً",
  "Promotion summary": "ملخص الترويج",
  "Next step": "الخطوة التالية",
  "Choose dates to see booked space.": "اختر التواريخ لمعرفة المساحة المحجوزة.",
  "Could not load booked space.": "تعذر تحميل المساحة المحجوزة.",
  "Booked space for these dates": "المساحة المحجوزة لهذه التواريخ",
  "Cairo": "القاهرة",
  "booked places per day": "مكان محجوز يومياً",
  "minimum free places per day": "أقل عدد أماكن متاحة يومياً",
  "Some dates are full. Extra bookings rotate; check the warning after saving.": "بعض التواريخ ممتلئة. الحجوزات الإضافية تتناوب؛ راجع التنبيه بعد الحفظ.",
  "Campaign created with capacity warnings.": "تم إنشاء الحملة مع تنبيهات للسعة.",
  "Capacity warning": "تنبيه السعة",
  "Could not save the campaign.": "تعذر حفظ الحملة.",
  "Could not create the campaign.": "تعذر إنشاء الحملة.",
  "Manage booked promotions, serving state, advertiser records and performance.": "إدارة الترويج المحجوز وحالة العرض وبيانات المعلنين والأداء.",
  "Showing campaigns for the selected surface.": "عرض حملات موضع العرض المختار.",
  "Manage Top 10": "إدارة أفضل ١٠",
  'Page sections': 'أقسام الصفحة',
  'Session expired': 'انتهت الجلسة',
  'Signing out…': 'جارٍ تسجيل الخروج…',
  'Enter a valid payment date.': 'أدخل تاريخ دفع صحيحاً.',
  'New subscription': 'اشتراك جديد',
  'Renew subscription': 'تجديد الاشتراك',
  'Plan name': 'اسم الخطة',
  'Start date (Cairo)': 'تاريخ البداية (القاهرة)',
  'End date (inclusive)': 'تاريخ النهاية (شامل)',
  'Subscription notes': 'ملاحظات الاشتراك',
  'First payment (EGP, optional)': 'الدفعة الأولى (جنيه، اختياري)',
  'Payment method': 'طريقة الدفع',
  'Payment date': 'تاريخ الدفع',
  'Payment notes': 'ملاحظات الدفع',
  'Cash': 'نقداً',
  'Bank transfer': 'تحويل بنكي',
  'Wallet': 'محفظة',
  'Confirm': 'تأكيد',
  'Back': 'رجوع',
  'Saved': 'تم الحفظ',
  'Saving…': 'جارٍ الحفظ…',
  'InstaPay': 'إنستاباي',
  "14-day free trial": "تجربة مجانية لمدة ١٤ يوماً",
  "1-month free trial": "تجربة مجانية لمدة شهر",
  "1 month": "شهر واحد",
  "2 months": "شهران",
  "3 months": "٣ أشهر",
  "6 months": "٦ أشهر",
  "Trial": "تجربة مجانية",
  "Free trial: no payment is recorded": "تجربة مجانية: لا يتم تسجيل أي دفعة",
  "Already used on": "استُخدمت بالفعل في",
  "Confirm that this place may receive another free trial.": "أؤكد السماح لهذا المكان بالحصول على تجربة مجانية أخرى.",
  "Choose a length or enter your own dates. Nothing is saved until you confirm.": "اختر المدة أو أدخل تواريخك. لا يُحفظ شيء قبل التأكيد.",
  "Subscription length": "مدة الاشتراك",
  "Enter a valid start and end date.": "أدخل تاريخي بداية ونهاية صحيحين.",
  "Plan name is required.": "اسم الخطة مطلوب.",
  "These dates overlap an existing subscription for this place. Choose another date range.": "هذه التواريخ تتداخل مع اشتراك قائم لهذا المكان. اختر فترة أخرى.",
  "DD/MM/YYYY": "يوم/شهر/سنة",
  "Open calendar": "فتح التقويم",
  "Previous month": "الشهر السابق",
  "Next month": "الشهر التالي",
  "Choose date": "اختر التاريخ",
  "days": "يوماً",
  "Open profile menu": "فتح قائمة الحساب",
  "Free WiFi": "واي فاي مجاني",
  "Breadcrumb": "مسار التنقل",
  "category-slug": "مثال: category-slug",
  "city-slug": "مثال: city-slug",
  "auto-generated from the name": "يُنشأ تلقائياً من الاسم",
  "Select city": "اختر المدينة",
  "Select category": "اختر التصنيف",
  "https://maps.app.goo.gl/…": "مثال: https://maps.app.goo.gl/…",
  "Remove photo": "إزالة الصورة",
  "Move left": "نقل إلى اليسار",
  "Move right": "نقل إلى اليمين",
  "Set as cover": "تعيين كصورة غلاف",
  "Delete photo": "حذف الصورة",
  "Delete video": "حذف الفيديو",
  "Image preview": "معاينة الصورة",
  "Close preview": "إغلاق المعاينة",
  "Move up": "نقل إلى الأعلى",
  "Move down": "نقل إلى الأسفل",
  "Delete section": "حذف القسم",
  "popular": "مثال: popular",
  "Restaurant": "مطعم",
  "restaurant": "مثال: restaurant",
  "Campaign totals": "إجماليات الحملة",
  "Loading campaigns": "جارٍ تحميل الحملات",
  "Inventory legend": "دليل المخزون",
  "Ads dashboard": "لوحة الإعلانات",
  "Copy API key": "نسخ مفتاح API",
  "/absolute/path/to/mcp/src/index.mjs": "مثال: /absolute/path/to/mcp/src/index.mjs",
  "https://your-api-host/v1": "مثال: https://your-api-host/v1",
  "Loading API keys": "جارٍ تحميل مفاتيح API",
  "Filter areas…": "تصفية المناطق…",
  "Filter areas": "تصفية المناطق",
  "Claude on my laptop": "كلود على حاسوبي",
  "View language": "لغة العرض",
  "Measure": "المقياس",
  "Search places to add…": "ابحث عن أماكن لإضافتها…",
  "01XXXXXXXXX": "مثال: 01XXXXXXXXX",
  "Search by name, name (En), or slug...": "ابحث بالاسم العربي أو الإنجليزي أو المعرّف...",
  "City · Category": "المدينة · التصنيف",
  "Placement · City": "الموضع · المدينة",
  "Edit pricing": "تعديل الأسعار",
  "5argny taps": "نقرات خرجني",
  "Photos": "الصور",
  "Impr.": "الظهور",
  "Khargny — dashboard home": "خرجني — الصفحة الرئيسية للوحة التحكم",
  "Campaign state": "حالة الحملة",
  'You cannot disable your own account': 'لا يمكنك تعطيل حسابك الخاص',
  'You cannot delete your own account': 'لا يمكنك حذف حسابك الخاص',
  'Could not load subscribers.': 'تعذر تحميل المشتركين.', 'another subscriber': 'مشترك آخر',
  'Previous page': 'الصفحة السابقة', 'Next page': 'الصفحة التالية', 'Revoked keys stay visible.': 'تظل المفاتيح الملغاة ظاهرة.',
  'Available': 'المتاح', 'Linked here': 'المرتبط هنا',
  'Linked to': 'مرتبط بـ', 'Owner': 'المشترك المسؤول', 'Any owner': 'أي مشترك',
  'No subscriber': 'بدون مشترك', 'Choose subscriber': 'اختر مشتركاً',
  'Search subscribers': 'ابحث عن المشتركين', 'Pagination': 'التنقل بين الصفحات',
  'Rows per page': 'صفوف في الصفحة', 'More actions': 'إجراءات أخرى',
  'Waiting for results': 'في انتظار النتائج',

  'Check the week below before saving — pasted text is a starting point, not a source of truth.': 'راجع الأسبوع أدناه قبل الحفظ؛ النص الملصق نقطة بداية وليس مصدراً مؤكداً.',
  'Or set specific days': 'أو حدد أياماً بعينها', 'This week': 'هذا الأسبوع', 'places': 'أماكن',
  'No cities yet.': 'لا توجد مدن بعد.', 'No places have an area set yet.': 'لا توجد أماكن محددة المنطقة بعد.',
  'Booked capacity across national and city placements.': 'السعة المحجوزة للمواضع العامة ومواضع المدن.',
  'Report not found.': 'لم يتم العثور على التقرير.',
  'Ad inventory': 'السعة الإعلانية', 'Edit campaign': 'تعديل الحملة', 'Loading booking details…': 'جارٍ تحميل بيانات الحجز…',
  'Review and update a booked placement.': 'مراجعة موضع إعلان محجوز وتحديثه.',
  'Update the booking record and advertiser details.': 'تحديث بيانات الحجز والمعلن.',
  'Book a Featured or Top 10 placement for an active place.': 'حجز إعلان مميز أو ضمن أفضل ١٠ لمكان نشط.',
  'Manage booked placements, serving state, advertiser records and performance.': 'إدارة المواضع المحجوزة وحالة العرض وبيانات المعلنين والأداء.',
  'Inspect the earned ranking, sponsored slots and current fair-rotation queue.': 'معاينة ترتيب الأماكن والمواضع الممولة وقائمة التناوب العادل الحالية.',
  'Top 10 city': 'مدينة أفضل ١٠', 'Leave as All Egypt for the national list.': 'اتركها على كل مصر للقائمة العامة.',
  'Start date': 'تاريخ البداية', 'End date': 'تاريخ النهاية', 'Calendar dates are inclusive in Africa/Cairo.': 'تواريخ البداية والنهاية مشمولة بتوقيت القاهرة.',
  'Advertiser name': 'اسم المعلن', 'Advertiser phone': 'هاتف المعلن', 'Optional; stored for the admin team only.': 'اختياري؛ يحفظ لفريق الإدارة فقط.',
  'Amount paid': 'المبلغ المدفوع', 'Currency': 'العملة', 'Notes': 'ملاحظات', 'Optional internal notes; maximum 2,000 characters.': 'ملاحظات داخلية اختيارية؛ حتى ٢٠٠٠ حرف.',
  'Live places': 'الأماكن المنشورة', 'Areas': 'المناطق', 'Drafts': 'المسودات', 'Across all cities': 'في كل المدن', 'Not visible to visitors': 'غير ظاهرة للزوار',
  'Free': 'متاح', 'Partly sold': 'محجوز جزئياً', 'Full': 'مكتمل', 'Oversold': 'تجاوز السعة',
  'Previous 4 weeks': 'الأسابيع الأربعة السابقة', 'Next 4 weeks': 'الأسابيع الأربعة التالية',
  'Resume': 'استئناف', 'Pause': 'إيقاف مؤقت', 'End': 'إنهاء',
  'Give AI assistants scoped access. Create, copy once, and revoke your own keys.': 'منح المساعدين صلاحيات محددة. أنشئ مفاتيحك وانسخها مرة واحدة أو ألغها.',
  'Rotate your password. Other signed-in sessions will be revoked on the next refresh.': 'تغيير كلمة المرور. تنتهي الجلسات الأخرى عند التحديث التالي.',
  'Back to settings': 'العودة للإعدادات',
  'Search places...': 'ابحث عن الأماكن…', 'Search categories...': 'ابحث عن التصنيفات…', 'Search cities...': 'ابحث عن المدن…',
  'Search tags...': 'ابحث عن الوسوم…', 'Search amenities...': 'ابحث عن المرافق…', 'Search admins...': 'ابحث عن المسؤولين…',
  'Search region': 'البحث عن منطقة', 'Filter by city': 'التصفية حسب المدينة', 'Search area — zamalek, nasr city, naama bay, الزمالك…': 'ابحث عن منطقة — الزمالك، مدينة نصر، خليج نعمة…',
  '← Settings': 'الإعدادات →', 'Connect AI assistants without sharing your admin password.': 'ربط مساعدي الذكاء الاصطناعي دون مشاركة كلمة مرورك.',
  'Create key': 'إنشاء مفتاح', 'Permissions remain capped by each owner&apos;s current role; disabling an owner disables their keys.': 'تظل الصلاحيات ضمن دور صاحب المفتاح الحالي؛ تعطيل صاحبه يعطل مفاتيحه.',
  'Could not verify your role.': 'تعذر التحقق من دورك.', 'Retry session': 'إعادة التحقق من الجلسة',
  'Could not load keys. Check your session and use Refresh to retry.': 'تعذر تحميل المفاتيح. تحقق من جلستك ثم استخدم التحديث للمحاولة مجدداً.',
  'Owner:': 'الصاحب:', '· 25 per page. Revoked keys stay visible.': '· ٢٥ في الصفحة. تظل المفاتيح الملغاة ظاهرة.',
  'will immediately lose access.': 'سيفقد الوصول فوراً.', 'The credential cannot be reactivated; its owner can create a replacement.': 'لا يمكن إعادة تفعيل المفتاح؛ يستطيع صاحبه إنشاء بديل.',
  'Give an AI assistant access within your own admin role. Keys cannot manage accounts, log in or create other keys.': 'امنح مساعداً صلاحيات ضمن دورك الإداري. لا يمكن للمفاتيح إدارة الحسابات أو تسجيل الدخول أو إنشاء مفاتيح أخرى.',
  'Viewers can create read-only keys. Editing and deleting require an admin role.': 'يمكن للمشاهدين إنشاء مفاتيح للقراءة فقط. يتطلب التعديل والحذف دور مسؤول.',
  'Deletion can permanently remove media files. Give delete permission only when necessary. Closing while creation is in progress can leave a key you must revoke and recreate.': 'قد يحذف الإجراء ملفات الوسائط نهائياً. امنح صلاحية الحذف عند الضرورة فقط. إغلاق النافذة أثناء الإنشاء قد يترك مفتاحاً عليك إلغاؤه وإنشاء بديل له.',
  'MCP entrypoint on the AI&apos;s computer': 'مسار تشغيل MCP على جهاز المساعد', 'API base URL (including /v1)': 'رابط API الأساسي (شاملاً /v1)',
  'Enter an absolute index.mjs path and an HTTPS API base URL ending in /v1 to enable Copy config. Never put the key in either field.': 'أدخل مسار index.mjs كاملاً ورابط API آمناً ينتهي بـ /v1 لتفعيل نسخ الإعدادات. لا تضع المفتاح في أي من الحقلين.',
  'Requires Node 22+ and the backend repository&apos;s mcp folder on the AI&apos;s computer. Replace the path before copying. Never commit this configuration or share it in chat. ZadLoop&apos;s import format is not independently verified; use its command, args and environment fields if JSON import is unavailable.': 'يتطلب Node 22 أو أحدث ومجلد mcp من مشروع الخادم على جهاز المساعد. استبدل المسار قبل النسخ. لا تحفظ الإعدادات في المستودع ولا تشاركها في المحادثات. صيغة استيراد ZadLoop غير مؤكدة؛ استخدم حقول الأمر والوسائط والبيئة إذا لم يتوفر استيراد JSON.',
  'For local-file uploads, add KHARGNY_UPLOAD_ROOT to the client&apos;s environment with one absolute local upload folder. Local uploads are disabled without it; URL uploads still work. See mcp/README.md for the exact field to add.': 'لرفع ملفات محلية، أضف KHARGNY_UPLOAD_ROOT إلى بيئة العميل بمسار كامل لمجلد رفع محلي واحد. الرفع المحلي معطل بدونه؛ يظل الرفع بالرابط متاحاً. راجع mcp/README.md للحقل المطلوب.',
  'Pick a strong password. Other browsers signed in with this account will be signed out on the next refresh.': 'اختر كلمة مرور قوية. تنتهي جلسات الحساب على المتصفحات الأخرى عند التحديث التالي.',
  'Reset all content': 'إعادة ضبط كل المحتوى', 'Reset all content…': 'إعادة ضبط كل المحتوى…', 'Delete all content?': 'حذف كل المحتوى؟',
  'Permanently deletes every place, city, category, amenity, tag and uploaded photo or video — a clean slate. Admin accounts, sign-ins and the audit log are kept. This cannot be undone and no backup is taken.': 'يحذف نهائياً كل الأماكن والمدن والتصنيفات والمرافق والوسوم والصور والفيديوهات المرفوعة. تبقى حسابات المسؤولين وجلساتهم وسجل التدقيق. لا يمكن التراجع ولا تؤخذ نسخة احتياطية.',
  'This is irreversible. Everything listed below is destroyed, including the files in storage.': 'لا يمكن التراجع. يحذف كل ما هو موضح أدناه، بما فيه الملفات المخزنة.',
  'Checking what would be deleted…': 'جارٍ التحقق مما سيحذف…', 'There is no content to delete — everything is already empty.': 'لا يوجد محتوى للحذف؛ كل الأقسام فارغة بالفعل.',
  'files in storage': 'ملفات مخزنة', 'Kept:': 'يبقى:', 'Type': 'اكتب', 'to confirm': 'للتأكيد',
  'Places in “': 'الأماكن في «', 'Search the catalog to add places, drag order with the arrows, and save. This section shows exactly these places, in this order, on the homepage and app.': 'ابحث في الدليل لإضافة أماكن ورتبها بالأسهم ثم احفظ. يعرض هذا القسم هذه الأماكن بهذا الترتيب في الصفحة الرئيسية والتطبيق.',
  'Added': 'تمت الإضافة', 'In this section (': 'في هذا القسم (', 'Loading…': 'جارٍ التحميل…', 'No places yet — search above to add some.': 'لا توجد أماكن بعد؛ ابحث أعلاه لإضافتها.', 'Save places': 'حفظ الأماكن',
  'Ad campaigns': 'الحملات الإعلانية', 'Ads inventory': 'السعة الإعلانية',
  'View and manage booked sponsored placements.': 'عرض مواضع الإعلانات الممولة المحجوزة وإدارتها.',
  'The place&apos;s photo gallery — pick several at once or drag &amp; drop them in. Drag a photo (or use the arrows) to set the order they appear in the public carousel. The first photo is this place&apos;s cover (list thumbnail + detail hero); use &ldquo;Set cover&rdquo; to promote another one. Separate from a city&apos;s own cover photo, which lives in the Cities tab.': 'معرض صور المكان؛ اختر عدة صور أو اسحبها وأفلتها. اسحب صورة أو استخدم الأسهم لترتيبها في المعرض العام. الصورة الأولى غلاف المكان في القائمة وصفحة التفاصيل؛ استخدم «تعيين كغلاف» لاختيار أخرى. غلاف المدينة مستقل ويعدل في تبويب المدن.',
  ': full control.': ': جميع الصلاحيات.', ': content management.': ': إدارة المحتوى.', ': read-only.': ': عرض فقط.',
  'The account is removed from this list, its sessions end immediately and its email becomes available again. What they did stays in the audit log. This cannot be undone — use Disable instead if you may want them back.': 'يحذف الحساب من القائمة وتنتهي جلساته فوراً ويصبح بريده متاحاً مجدداً. تبقى إجراءاته في سجل التدقيق. لا يمكن التراجع؛ استخدم التعطيل إذا كنت تريد إعادته لاحقاً.',
  'The admin will be marked inactive and signed out within one request. They won&apos;t be able to log in again until you re-enable them.': 'يعطل حساب المسؤول وتنتهي جلسته خلال طلب واحد. لن يتمكن من الدخول حتى تعيد تفعيله.',
  'The admin will be able to sign in again immediately.': 'سيتمكن المسؤول من تسجيل الدخول فوراً.',
  'Set to &quot;Disabled&quot; to revoke this admin&apos;s access. Use the Disable action on the list page for the recommended flow (it also handles the sign-out side effect).': 'اختر «معطل» لإلغاء وصول المسؤول. يفضل استخدام إجراء التعطيل في صفحة القائمة لأنه ينهي الجلسات أيضاً.',
  'Showing campaigns linked from an inventory scope or day.': 'عرض الحملات المرتبطة بنطاق سعة أو يوم.',
  'Ranked by rating, saves, directions and views. Sponsored rows replace the rank number.': 'الترتيب حسب التقييم والحفظ وطلبات الاتجاهات والمشاهدات. تحل علامة التمويل محل رقم الترتيب للحملات الممولة.',
  'No ranking candidates for this scope.': 'لا توجد أماكن مؤهلة للترتيب في هذا النطاق.',
  'All live Top 10 campaigns for this scope. “Shown now” reflects the current 10-minute bucket.': 'كل حملات أفضل ١٠ المباشرة في هذا النطاق. «معروض الآن» يعكس فترة التناوب الحالية ومدتها ١٠ دقائق.',
  'No live sponsored campaigns in this scope.': 'لا توجد حملات ممولة مباشرة في هذا النطاق.',
  'Khargny · خرجني — Sponsored placement report': 'خرجني — تقرير موضع الإعلان الممول',
  'Placement:': 'موضع الإعلان:', 'Scope:': 'النطاق:', 'Dates:': 'التواريخ:', 'Timezone:': 'المنطقة الزمنية:',
  'Daily performance begins when the scheduled campaign starts.': 'يبدأ الأداء اليومي مع بداية الحملة المجدولة.',
  'Taps (right axis)': 'النقرات (المحور الأيمن)', 'Daily impressions and taps': 'مرات الظهور والنقرات اليومية',
  'Bar chart from': 'رسم بالأعمدة من', 'through': 'حتى', 'impressions,': 'مرة ظهور،', 'taps': 'نقرة',
  'No icon matches “': 'لا توجد أيقونة تطابق «', 'total)': 'إجمالاً)',
  'Any child categories are reassigned to this category&apos;s parent. If places are still assigned to it, those places are set to': 'تنقل التصنيفات الفرعية إلى التصنيف الرئيسي. إذا بقيت أماكن مرتبطة به، تحول حالتها إلى',
  'draft': 'مسودة', '(hidden from the site) and the category is removed from the dashboard rather than erased from the database — places must keep pointing at a category that exists.': '(مخفية عن الموقع) ويزال التصنيف من لوحة التحكم دون محوه من قاعدة البيانات؛ يجب أن تبقى الأماكن مرتبطة بتصنيف موجود.',
  'Delete this category?': 'حذف هذا التصنيف؟', 'This will remove the category and break any place currently filed under it. This cannot be undone.': 'سيزيل هذا التصنيف ويؤثر على الأماكن المرتبطة به. لا يمكن التراجع عن ذلك.',
  'Back to categories': 'العودة للتصنيفات', 'Name (English)': 'الاسم بالإنجليزية',
  'Cover photo': 'صورة الغلاف', 'Cover photo *': 'صورة الغلاف *', 'Add photo': 'إضافة صورة', 'Remove': 'إزالة',
  'Governorate *': 'المحافظة *', 'Regions / areas in this city': 'المناطق والأحياء في هذه المدينة',
  'Description (Arabic)': 'الوصف بالعربية', 'Description (English)': 'الوصف بالإنجليزية',
  'No governorate matches “': 'لا توجد محافظة تطابق «', 'area': 'منطقة', 'selected': 'محدد', 'No areas match “': 'لا توجد مناطق تطابق «',
  'Pick the city (governorate) first — its areas appear here to choose from.': 'اختر المدينة (المحافظة) أولاً لتظهر مناطقها هنا.',
  'Deleted': 'محذوف', 'English': 'الإنجليزية', 'active)': 'نشط)', 'Add your first city': 'إضافة أول مدينة',
  'This city will be hidden from the public list. Areas/districts under this city will remain (no cascade).': 'ستخفى المدينة من القائمة العامة. تبقى مناطقها وأحياؤها دون حذف.',
  'Restore': 'استعادة', 'The city will be restored to its prior status and reappear on the public list.': 'تستعاد المدينة لحالتها السابقة وتظهر مجدداً في القائمة العامة.',
  'Back to cities': 'العودة للمدن', 'Recommended 1200×800 (3:2), min 800×600. 16:9 also works. Auto-optimized to WebP.': 'يفضل ١٢٠٠×٨٠٠ (٣:٢)، والحد الأدنى ٨٠٠×٦٠٠. تقبل ١٦:٩ أيضاً. تحسن تلقائياً إلى WebP.',
  'Couldn&apos;t load insights.': 'تعذر تحميل الإحصاءات.',
  'The analytics endpoint didn&apos;t respond. This is the only thing on this page that failed — the rest of the dashboard is unaffected.': 'لم تستجب خدمة الإحصاءات. هذا الجزء فقط تعذر تحميله؛ بقية لوحة التحكم لم تتأثر.',
  'Engagement': 'التفاعل', 'Catalogue': 'الدليل', 'Ranked by': 'الترتيب حسب', 'Most-viewed places': 'الأماكن الأكثر مشاهدة', 'No places yet.': 'لا توجد أماكن بعد.',
  'Place Details': 'بيانات المكان', 'Auto-filled from the name and kept unique on save. Edit it if you want a custom URL.': 'يملأ تلقائياً من الاسم ويظل فريداً عند الحفظ. عدله إذا أردت رابطاً مخصصاً.',
  'City *': 'المدينة *', 'Category *': 'التصنيف *', 'Area *': 'المنطقة *', 'Google Maps link *': 'رابط خرائط Google *',
  'Pick which amenities this place has. Only amenities created in the catalog appear.': 'اختر مرافق المكان. تظهر فقط المرافق التي أنشئت في الدليل.',
  'No amenities exist in the catalog yet.': 'لا توجد مرافق في الدليل بعد.', 'Create amenities →': 'إنشاء مرافق ←',
  'Tag this place (family-friendly, outdoor…). Only tags created in the catalog appear.': 'أضف وسوم المكان (مناسب للعائلة، في الهواء الطلق…). تظهر فقط وسوم الدليل.',
  'No tags exist in the catalog yet.': 'لا توجد وسوم في الدليل بعد.', 'Create tags →': 'إنشاء وسوم ←',
  'Opening hours': 'مواعيد العمل', 'Set the week now, or leave it and add hours later on the place.': 'حدد مواعيد الأسبوع الآن أو أضفها لاحقاً من صفحة المكان.',
  'Media': 'الوسائط', 'The cover is on the Details tab. Add more gallery photos here — they upload with the place.': 'الغلاف في تبويب البيانات. أضف صور المعرض هنا لرفعها مع المكان.',
  'Current:': 'الحالي:', '(not in the list — pick one below to normalise it)': '(غير موجود في القائمة؛ اختر منطقة أدناه لتوحيدها)', 'No region matches “': 'لا توجد منطقة تطابق «',
  'Quick presets — applies to every day': 'قوالب سريعة تطبق على كل الأيام', 'Paste hours from Google Maps': 'لصق المواعيد من خرائط Google',
  'On Google Maps, expand the opening hours, select the whole block and copy it. Paste it here — English or Arabic, 12- or 24-hour, &ldquo;Closed&rdquo; and &ldquo;Open 24 hours&rdquo; all work.': 'افتح مواعيد العمل في خرائط Google وانسخها بالكامل ثم الصقها هنا. يدعم العربية والإنجليزية ونظامي ١٢ و٢٤ ساعة و«مغلق» و«مفتوح ٢٤ ساعة».',
  'Filled': 'تم ملء', 'day': 'يوم', 'Check the week below before saving.': 'راجع مواعيد الأسبوع أدناه قبل الحفظ.',
  'Pick days, then set their hours': 'اختر الأيام ثم حدد مواعيدها', 'The week': 'الأسبوع', 'Closed': 'مغلق',
  'Any status': 'كل الحالات', 'Any city': 'كل المدن', 'Any category': 'كل التصنيفات', 'Any media': 'كل الوسائط',
  'Has media': 'توجد وسائط', 'Needs media': 'يحتاج وسائط', 'Failed to load places': 'تعذر تحميل الأماكن', 'Yes': 'نعم', 'No': 'لا',
  'This place will be hidden from the public list. You can restore it later from the Deleted filter.': 'سيخفى المكان من القائمة العامة. يمكنك استعادته لاحقاً من فلتر المحذوفات.',
  'The place returns as a draft — it stays hidden from the public list until you publish it again.': 'يعود المكان كمسودة؛ يظل مخفياً عن القائمة العامة حتى تنشره مجدداً.',
  'Failed to load place': 'تعذر تحميل المكان', 'Place not found': 'المكان غير موجود', 'Area (region)': 'المنطقة', 'Google Maps link': 'رابط خرائط Google',
  'Pick which amenities this place has. Changes are sent to the public detail on save.': 'اختر مرافق المكان. تظهر التغييرات في بيانات المكان العامة عند الحفظ.',
  'Place is soft-deleted. Amenities are read-only.': 'المكان محذوف مؤقتاً. المرافق للعرض فقط.', 'Failed to load amenities catalog.': 'تعذر تحميل دليل المرافق.',
  'Create amenities in catalog →': 'إنشاء مرافق في الدليل ←', 'No amenities assigned yet — pick from the catalog.': 'لا توجد مرافق مرتبطة بعد؛ اختر من الدليل.',
  'Tag this place (family-friendly, outdoor…) so visitors can filter by vibe. Changes are sent to the public detail on save.': 'أضف وسوم المكان (مناسب للعائلة، في الهواء الطلق…) لتسهيل البحث للزوار. تظهر التغييرات للعامة عند الحفظ.',
  'Place is soft-deleted. Tags are read-only.': 'المكان محذوف مؤقتاً. الوسوم للعرض فقط.', 'Failed to load tags catalog.': 'تعذر تحميل دليل الوسوم.',
  'Create tags in catalog →': 'إنشاء وسوم في الدليل ←', 'No tags assigned yet — pick from the catalog.': 'لا توجد وسوم مرتبطة بعد؛ اختر من الدليل.',
  'Set when this place is open each day. Mark a day closed to hide its hours on the public detail. Saved with the place.': 'حدد مواعيد العمل اليومية. حدد اليوم كمغلق لإخفاء مواعيده عن العامة. تحفظ مع بيانات المكان.',
  'Place is soft-deleted. Hours are read-only.': 'المكان محذوف مؤقتاً. المواعيد للعرض فقط.', 'Photos &amp; videos': 'الصور والفيديوهات',
  'Place is soft-deleted. Photos are read-only.': 'المكان محذوف مؤقتاً. الصور للعرض فقط.', 'No photos yet — add the first one above.': 'لا توجد صور بعد؛ أضف أول صورة أعلاه.',
  'Cover': 'الغلاف', 'Set cover': 'تعيين كغلاف', 'Videos': 'الفيديوهات', 'Upload short clips (MP4/WebM, up to 100MB each). They stream in the place&apos;s public gallery.': 'ارفع مقاطع قصيرة (MP4/WebM، حتى ١٠٠ ميجابايت لكل مقطع). تعرض في معرض المكان العام.', 'No videos yet.': 'لا توجد فيديوهات بعد.',
  'Insights': 'الإحصاءات', 'What visitors are doing across the catalogue.': 'نشاط الزوار في دليل الأماكن.',
  'Settings': 'الإعدادات', 'Manage your own account.': 'إدارة حسابك.', 'Account': 'الحساب',
  'Settings specific to your admin account.': 'إعدادات حسابك الإداري.', 'Danger zone': 'إجراءات حساسة',
  'Irreversible actions affecting the entire site. Super admin only.': 'إجراءات لا يمكن التراجع عنها تؤثر على الموقع بالكامل. للمسؤول الأعلى فقط.',
  'Admins': 'المسؤولون', 'Add admin': 'إضافة مسؤول', 'Edit admin': 'تعديل المسؤول', 'Admin details': 'بيانات المسؤول',
  'Email': 'البريد الإلكتروني', 'Password': 'كلمة المرور', 'Initial password': 'كلمة المرور الأولية',
  'Role': 'الدور', 'Super admin': 'مسؤول أعلى', 'Admin': 'مسؤول', 'Viewer': 'مشاهد', 'Editor': 'محرر',
  'Active': 'نشط', 'Disabled': 'معطل', 'Draft': 'مسودة', 'Status': 'الحالة', 'Last login': 'آخر دخول',
  'Created': 'تاريخ الإنشاء', 'Actions': 'الإجراءات', 'Action': 'الإجراء', 'Edit': 'تعديل', 'Delete': 'حذف',
  'Disable': 'تعطيل', 'Enable': 'تفعيل', '(you)': '(أنت)', 'Cancel': 'إلغاء', 'Retry': 'إعادة المحاولة',
  'Refresh': 'تحديث', 'Previous': 'السابق', 'Prev': 'السابق', 'Next': 'التالي', 'Page': 'الصفحة', 'of': 'من',
  'Back to admins': 'العودة للمسؤولين', 'Admin not found': 'المسؤول غير موجود', 'No admins yet': 'لا يوجد مسؤولون بعد',
  'Failed to load admin': 'تعذر تحميل المسؤول', 'Failed to load admins': 'تعذر تحميل المسؤولين',
  'Admin management is restricted to super admins.': 'إدارة المسؤولين متاحة للمسؤول الأعلى فقط.',
  'You don&apos;t have access to this page': 'ليس لديك صلاحية لهذه الصفحة', 'Add the first admin': 'إضافة أول مسؤول',
  'Delete admin': 'حذف المسؤول', 'Disable admin': 'تعطيل المسؤول', 'Re-enable': 'إعادة التفعيل',
  'Manage who can sign in to the dashboard and what they can do.': 'إدارة من يمكنه دخول لوحة التحكم وصلاحياته.',
  'Must be at least 8 characters. The admin should change this on first login.': 'ثمانية أحرف على الأقل. على المسؤول تغييرها عند أول دخول.',
  'Email is set at creation and cannot be changed here.': 'يحدد البريد عند الإنشاء ولا يمكن تغييره هنا.',
  'You cannot change your own role.': 'لا يمكنك تغيير دورك.', 'Created:': 'تاريخ الإنشاء:', 'Last login:': 'آخر دخول:',
  'Dashboard': 'لوحة التحكم', 'New': 'جديد', 'Name': 'الاسم', 'Name *': 'الاسم *', 'English Name': 'الاسم بالإنجليزية',
  'Arabic Name': 'الاسم بالعربية', 'Name (Arabic) *': 'الاسم بالعربية *', 'Name (English) *': 'الاسم بالإنجليزية *',
  'Slug': 'المعرف النصي', 'Slug *': 'المعرف النصي *', 'Icon': 'الأيقونة', 'Sort order': 'ترتيب العرض',
  'Categories': 'التصنيفات', 'Add Category': 'إضافة تصنيف', 'New Category': 'تصنيف جديد', 'Edit Category': 'تعديل التصنيف',
  'Category Details': 'بيانات التصنيف', 'Parent category': 'التصنيف الرئيسي', '(none — top-level)': '(بدون — المستوى الرئيسي)',
  'Failed to load categories': 'تعذر تحميل التصنيفات', 'Failed to load category': 'تعذر تحميل التصنيف',
  'Category not found': 'التصنيف غير موجود', 'Add your first category': 'إضافة أول تصنيف',
  'Cities': 'المدن', 'Add City': 'إضافة مدينة', 'New City': 'مدينة جديدة', 'Edit City': 'تعديل المدينة',
  'City Details': 'بيانات المدينة', 'Failed to load cities': 'تعذر تحميل المدن', 'Failed to load city': 'تعذر تحميل المدينة',
  'City not found': 'المدينة غير موجودة', 'Region': 'المنطقة', 'Parent city': 'المدينة الرئيسية',
  'Amenities': 'المرافق', 'Add Amenity': 'إضافة مرفق', 'New Amenity': 'مرفق جديد', 'Edit Amenity': 'تعديل المرفق',
  'Amenity Details': 'بيانات المرفق', 'Failed to load amenities': 'تعذر تحميل المرافق',
  'Failed to load amenity': 'تعذر تحميل المرفق', 'Amenity not found': 'المرفق غير موجود', 'No amenities found': 'لم يتم العثور على مرافق',
  'Tags': 'الوسوم', 'Add Tag': 'إضافة وسم', 'New Tag': 'وسم جديد', 'Edit Tag': 'تعديل الوسم', 'Tag Details': 'بيانات الوسم',
  'Failed to load tags': 'تعذر تحميل الوسوم', 'Failed to load tag': 'تعذر تحميل الوسم', 'Tag not found': 'الوسم غير موجود', 'No tags found': 'لم يتم العثور على وسوم',
  'Places': 'الأماكن', 'Place': 'المكان', 'Add Place': 'إضافة مكان', 'New Place': 'مكان جديد', 'Edit Place': 'تعديل المكان',
  'City': 'المدينة', 'Category': 'التصنيف', 'Description': 'الوصف', 'Address': 'العنوان', 'Phone': 'الهاتف',
  'Latitude': 'خط العرض', 'Longitude': 'خط الطول', 'Website': 'الموقع الإلكتروني', 'Featured': 'مميز',
  'Clear': 'مسح', 'Selected:': 'المحدد:', 'All cities (27 governorates)': 'كل المدن (٢٧ محافظة)',
  'Opening time': 'وقت الفتح', 'Closing time': 'وقت الإغلاق', 'to': 'إلى', 'All': 'الكل', 'None': 'بدون',
  'Fill hours from this': 'ملء المواعيد من النص', 'Mark closed': 'تحديد كمغلق', 'Sun–Thu': 'الأحد–الخميس', 'Fri–Sat': 'الجمعة–السبت',
  'Sunday': 'الأحد', 'Monday': 'الاثنين', 'Tuesday': 'الثلاثاء', 'Wednesday': 'الأربعاء', 'Thursday': 'الخميس', 'Friday': 'الجمعة', 'Saturday': 'السبت',
  'Campaigns': 'الحملات', 'Inventory': 'السعة الإعلانية', 'Top 10 preview': 'معاينة أفضل ١٠', 'New campaign': 'حملة جديدة',
  'Placement': 'موضع الإعلان', 'Featured · national': 'مميز · على مستوى مصر', 'Top 10': 'أفضل ١٠', 'All Egypt': 'كل مصر',
  'Advertiser': 'المعلن', 'Advertiser and payment record': 'بيانات المعلن والدفع', 'Dates': 'التواريخ', 'Amount': 'المبلغ',
  'Impressions': 'مرات الظهور', 'Taps': 'النقرات', 'CTR': 'معدل النقر', 'State': 'الحالة', 'Clear filter': 'مسح الفلتر',
  'Open report': 'فتح التقرير', 'Open campaign': 'فتح الحملة', 'Campaign created.': 'تم إنشاء الحملة.',
  'Inventory warning': 'تنبيه السعة', 'No campaigns in this view': 'لا توجد حملات في هذا العرض',
  'Try another state or create a campaign to book inventory.': 'جرّب حالة أخرى أو أنشئ حملة لحجز السعة.',
  'The booking is saved. Oversold campaigns rotate fairly.': 'تم حفظ الحجز. تتناوب الحملات التي تجاوزت السعة بشكل عادل.',
  'Campaign targeting can only change while scheduled.': 'يمكن تغيير استهداف الحملة فقط أثناء جدولتها.',
  'Place, placement and city are locked because this campaign is no longer scheduled.': 'المكان والموضع والمدينة مقفلة لأن الحملة لم تعد مجدولة.',
  'City scope': 'نطاق المدينة', 'Eligible candidates': 'الأماكن المؤهلة', 'Ranked list': 'قائمة الترتيب',
  'Sponsored slot': 'موضع ممول', 'Score': 'النتيجة', 'Sponsored queue': 'قائمة الحملات الممولة', '4 weeks': '٤ أسابيع', 'Today': 'اليوم',
  'No inventory scopes available': 'لا توجد نطاقات سعة متاحة', 'Active city scopes will appear here when the API returns them.': 'تظهر نطاقات المدن النشطة هنا عند إتاحتها من الخدمة.',
  'Each cell shows booked / capacity. Select a booked day to view those campaigns.': 'تعرض كل خلية المحجوز / السعة. اختر يوماً محجوزاً لعرض حملاته.',
  'Scope': 'النطاق', 'Campaign': 'الحملة', 'Print / Save PDF': 'طباعة / حفظ PDF', 'Daily performance': 'الأداء اليومي',
  'Daily detail': 'التفاصيل اليومية', 'Date': 'التاريخ', 'Reach': 'الوصول', 'No daily rows yet.': 'لا توجد بيانات يومية بعد.',
  'How these numbers are measured': 'كيف تقاس هذه الأرقام', 'Views': 'المشاهدات', 'Saves': 'الحفظ', 'Directions': 'طلبات الاتجاهات',
  'Try again': 'حاول مرة أخرى', 'Where the engagement is': 'أين يحدث التفاعل', 'By city': 'حسب المدينة', 'By area': 'حسب المنطقة',
  'Storefront': 'واجهة الموقع', 'Homepage sections': 'أقسام الصفحة الرئيسية', 'Add a section': 'إضافة قسم',
  'Key *': 'المفتاح *', 'Kind *': 'النوع *', 'Top rated': 'الأعلى تقييماً', 'Recommended': 'موصى به', 'Custom (pinned)': 'مخصص (مثبت)',
  'Title (Arabic) *': 'العنوان بالعربية *', 'Title (English)': 'العنوان بالإنجليزية',
  'Control which sections appear on the public homepage and in what order.': 'تحديد الأقسام التي تظهر في الصفحة الرئيسية وترتيبها.',
  'No sections yet. Add one below — it will show on the homepage.': 'لا توجد أقسام بعد. أضف قسماً أدناه ليظهر في الصفحة الرئيسية.',
  'Footer &amp; social': 'التذييل والتواصل الاجتماعي', 'Shown in the website footer and the app. Leave a field blank to hide that icon.': 'تظهر في تذييل الموقع والتطبيق. اترك الحقل فارغاً لإخفاء أيقونته.',
  'API keys': 'مفاتيح API', 'Name / prefix': 'الاسم / البادئة', 'Permissions': 'الصلاحيات', 'Last used': 'آخر استخدام', 'Expires': 'انتهاء الصلاحية',
  'Revoke': 'إلغاء المفتاح', 'Revoke API key?': 'إلغاء مفتاح API؟', 'No keys on this page': 'لا توجد مفاتيح في هذه الصفحة',
  'Create a named key for each AI assistant so you can revoke access independently.': 'أنشئ مفتاحاً باسم لكل مساعد لتتمكن من إلغاء صلاحياته منفرداً.',
  'Your API key': 'مفتاح API الخاص بك', 'AI client': 'عميل الذكاء الاصطناعي', 'Copy config': 'نسخ الإعدادات',
  'Save this key now. It will not be shown again. Closing this dialog removes it from this page.': 'احفظ المفتاح الآن؛ لن يظهر مرة أخرى. إغلاق النافذة يزيله من الصفحة.',
  'I have saved it · Close': 'حفظته · إغلاق', 'Expiry (optional, your local time)': 'انتهاء الصلاحية (اختياري، بتوقيتك المحلي)',
  'Change password': 'تغيير كلمة المرور', 'Update your password': 'تحديث كلمة المرور', 'Current password': 'كلمة المرور الحالية',
  'New password': 'كلمة المرور الجديدة', 'Confirm new password': 'تأكيد كلمة المرور الجديدة',
  'At least 8 characters with 1 letter and 1 number.': 'ثمانية أحرف على الأقل، منها حرف ورقم.',
  'You will stay signed in on this device after the change.': 'ستبقى مسجلاً للدخول على هذا الجهاز بعد التغيير.',
  'Sign in': 'تسجيل الدخول', 'Signing in…': 'جارٍ تسجيل الدخول…', 'Khargny admin dashboard': 'لوحة إدارة خرجني',
  'Connection error. Try again.': 'تعذر الاتصال. حاول مرة أخرى.', 'Invalid email or password': 'البريد الإلكتروني أو كلمة المرور غير صحيحين',
  'Too many attempts. Try again in a few minutes.': 'محاولات كثيرة. حاول مجدداً بعد بضع دقائق.',
  "Monday 9 AM–10 PM Tuesday 9 AM–10 PM Wednesday Closed": "الاثنين ٩ صباحاً–١٠ مساءً\nالثلاثاء ٩ صباحاً–١٠ مساءً\nالأربعاء مغلق",
  "Link state": "حالة الربط",
  "View": "عرض",
};

export function translateDashboardCopy(value: string, lang: 'ar' | 'en') {
  if (lang === 'en') return value;
  const key = value.replace(/\s+/g, ' ').trim();
  const match = Object.entries(dashboardCopy).find(([candidate]) => candidate.replaceAll('&apos;', "'").replaceAll('&amp;', '&').replaceAll('&quot;', '"').replaceAll('&ldquo;', '“').replaceAll('&rdquo;', '”') === key);
  return match?.[1] ?? value;
}
