export const round8Copy: Record<string, string> = {
  "Extend 7 days": "تمديد ٧ أيام",
  "Send reminder": "إرسال تذكير",
  "Incomplete": "غير مكتمل",
  "How this is counted": "كيف نحسب هذه الأرقام",
  "Recent minutes are missing.": "بيانات الدقائق الأخيرة غير متاحة.",
  "Some minutes were not observed.": "لم تُرصد بعض الدقائق.",
  "Yesterday is not available for comparison.": "بيانات أمس غير متاحة للمقارنة.",
  "No counted activity in this breakdown.": "لا يوجد نشاط مسجّل في هذا التقسيم.",
  "Open holders to preview this rule.": "افتح الأماكن الحاملة للشارة لمعاينة هذه القاعدة.",
  "Something went wrong on this page": "حدث خطأ في هذه الصفحة",
  "The page hit an unexpected error. You can try again, or head back to the dashboard.": "حدث خطأ غير متوقع. يمكنك المحاولة مجددًا أو العودة إلى لوحة التحكم.",
  "Back to dashboard": "العودة إلى لوحة التحكم",
  "Maximum 100 at once": "بحد أقصى ١٠٠ في المرة",
  "Changed": "تغيّرت",
  "Likes": "الإعجابات",
  "Save icon": "أيقونة الحفظ",
  "Suggestions": "اقتراحات",
  "Likes in the selected period": "الإعجابات خلال الفترة المختارة",
  "New committed likes, not net of unlikes. Current place likes are a separate count.": "إعجابات جديدة مسجلة، دون طرح إلغاء الإعجاب. العدد الحالي للمكان مقياس منفصل.",
  "Could not load likes.": "تعذّر تحميل الإعجابات.",
  "The likes report does not support a platform split. Clear the platform filter to read it.": "تقرير الإعجابات لا يدعم التقسيم حسب المنصة. أزل فلتر المنصة لقراءته.",
  "Likes per day": "الإعجابات يوميًا",
  "Most liked places": "الأماكن الأكثر إعجابًا",
  "Ranked by new likes in this period, not the current total.": "مرتبة حسب الإعجابات الجديدة خلال هذه الفترة، لا حسب إجماليها الحالي.",
  "All activity": "كل النشاط",
  "With likes": "بإعجابات",
  "No likes": "دون إعجابات",
  "Manage tags": "إدارة الوسوم",
  "Keyword performance comes from owned search terms in this period. Manage the vocabulary in Content → Tags.": "أداء الكلمات من عبارات البحث التابعة لها خلال هذه الفترة. إدارة الكلمات في المحتوى ← الوسوم.",
  "No owned keyword searches in this period.": "لا توجد عمليات بحث مرتبطة بكلمات خلال هذه الفترة.",
  "All search outcomes": "كل نتائج البحث",
  "Could not load suggestions.": "تعذّر تحميل الاقتراحات.",
  "Each suggestion cites recorded evidence. Missing scopes and unknown counts never become recommendations.": "كل اقتراح يستند إلى أرقام مسجلة. لا نقدم توصيات عن نطاقات مفقودة أو أعداد مجهولة.",
  "Add it as a keyword": "أضفها ككلمة بحث",
  "Sell a campaign here": "بع حملة هنا",
  "Check its photos and prices": "راجع صوره وأسعاره",
  "searches found nothing in this period": "عملية بحث لم تجد نتائج خلال هذه الفترة",
  "selected period": "الفترة المختارة",
  "All suggestion types": "كل أنواع الاقتراحات",
  "No evidence-backed suggestions in the reports available for this period.": "لا توجد اقتراحات مدعومة بأرقام في التقارير المتاحة لهذه الفترة.",
  "Place engagement": "التفاعل مع المكان",
  "Views, saves and taps are lifetime counters. Likes are the current committed count; unavailable fields stay —.": "المشاهدات والحفظ وضغطات خارّجني أعداد تراكمية. الإعجابات هي العدد الحالي المسجل؛ البيانات غير المتاحة تظهر —.",
  "Sort places": "ترتيب الأماكن",
  "Default order": "الترتيب الافتراضي",
  "Most liked first": "الأكثر إعجابًا أولًا",
  "Select all places on this page": "تحديد كل الأماكن في هذه الصفحة",
  "Bulk place status": "تغيير حالة الأماكن جماعيًا",
  "Activate selected places": "تفعيل الأماكن المحددة",
  "Deactivate selected places": "تعطيل الأماكن المحددة",
  "Clear selection": "إلغاء التحديد",
  "Activate selected places?": "تفعيل الأماكن المحددة؟",
  "Deactivate selected places?": "تعطيل الأماكن المحددة؟",
  "Hidden from visitors; promotions pause; the subscription is untouched.": "تُخفى عن الزوار وتتوقف ترويجاتها، دون تغيير الاشتراك.",
  "These places become active. Visitor visibility still depends on approved media.": "تصبح هذه الأماكن نشطة. ظهورها للزوار يظل مرتبطًا بالوسائط المعتمدة.",
  "Could not change places. Selection is kept.": "تعذّر تغيير الأماكن. احتفظنا بالتحديد.",
  "Place status results": "نتائج تغيير حالة الأماكن",
  "Successful places are unticked. Places that could not change stay selected.": "أُلغي تحديد الأماكن التي تغيرت بنجاح. الأماكن التي تعذّر تغييرها تظل محددة.",
  "Could not change": "تعذّر التغيير",
  "No reason supplied by the server.": "لم يرسل الخادم سببًا.",
  "Live activity is switched off. Historical reports are still available.": "النشاط المباشر متوقف. التقارير السابقة ما زالت متاحة.",
  "estimated visitor": "زائر تقديري",
  "Done": "تم",
  "Not shown": "غير ظاهر",
  "No approved media": "لا توجد وسائط معتمدة",
  "Merged into another place": "مدمج في مكان آخر",
  "Records": "السجلات"
};
